************************************************************************
trafficProcessorTable README
------------------------------------------------------------------------
  This readme file describes the code generated by mib2c (using the MIBs
  for Dummies (MFD) configuration file). The code generated was
  generated specifically for the following SNMP table:

     trafficProcessorTable

  Your code will be called when the snmp agent receives requests for
  the trafficProcessorTable table.  The agent will start by looking for the right
  row in your existing data to operate on, if one exists.


  Configuration Variables
  ------------------------------------------------------------
  Some variables used for code generation may be set to affect the code
  generation. You may override these variables by setting them in the
  file defaults/table-trafficProcessorTable.m2d, and then re-running mib2c.

    m2c_table_settable (currently '0')
    --------------------------------------------------------
    This variable determines whether or not code is generated to support
    MIB object which have an access of read-write or read-create. The
    default is set based on whether or not the table contains writable
    objects, but can be over-ridden.

    Syntax: @eval $m2c_table_settable = 0@


    m2c_table_dependencies (currently '0')
    --------------------------------------------------------
    This variable determines whether or not code is generated to support
    checking dependencies between columns, rows or tables. The default
    is set based on whether or not the table contains writable objects,
    but can be over-ridden.

    Syntax: @eval $m2c_table_dependencies = 0@


    m2c_table_row_creation (currently '0')
    --------------------------------------------------------
    This variable determines whether or not code is generated to support
    checking creation of new rows via SNMP. The default is set based on
    whether or not the table contains read-create objects, but can be
    over-ridden.

    Syntax: @eval $m2c_table_row_creation = 0@


    m2c_context_reg (currently 'netsnmp_data_list')
    --------------------------------------------------------
    This variable contains the structure name to typedef for the
    trafficProcessorTable_registration.

    During initilization, you will provide a pointer to a structure of
    this type. This pointer is used as a parameter to many functions so
    that you have access to your registration data. The default is a
    netsnmp_data_list pointer, which will allow you to keep multiple
    pointers tagged by a text name. If you have a new or existing structure
    you would rather use, you can redefine this variable.
    

    To avoid regenerating code, you may also change this typedef directly
    in the trafficProcessorTable.h header.

    Syntax: @eval $m2c_context_reg = "struct my_registration_context@


    m2c_data_context (currently 'generated')
    --------------------------------------------------------
    This variable contains the structure name to typedef for the
    trafficProcessorTable_data.

    This typedef is used in the row request context structure for the table,
    trafficProcessorTable_rowreq_ctx.

    The typedef in the primary table context will be used for the data and
    undo structure types. This structure should contain all the data
    needed for all the columns in the table. The default is 'generated',
    which will cuase a new data strcuture to be generated with data members
    for each column.

    To avoid regenerating code, you may also change this typedef directly
    in the trafficProcessorTable.h header.

    Syntax: @eval $m2c_data_context = "struct my_data_context"@


    m2c_data_allocate (currently '0')
    --------------------------------------------------------
    This variable determines whether or not the data context (see above)
    requires memory to be allocated. The default generated data structure
    does not. If you are using a custom data context which needs to
    allocate memory, override this value and two additional functions
    will be generated:

      trafficProcessorTable_allocate_data
      trafficProcessorTable_release_data

    Syntax: @eval $m2c_data_allocate = 1@


    m2c_data_init (currently '1')
    --------------------------------------------------------
    This variable determines whether or not the data context (see above)
    or any other items you have added to the table context requires
    initialization. The default generated data structure does not. If you
    are using a custom data context or have added items needing initialization
    to the table context, override this value and two additional functions
    will be generated:

      trafficProcessorTable_rowreq_ctx_init
      trafficProcessorTable_rowreq_ctx_cleanup

    Syntax: @eval 1 = 1@


    m2c_table_access (currently 'container-cached')
    ------------------------------------------------------------------
    This variable determines which data interface will be use to generate
    code for looking up data for a given index. The default is the
    'container-cached' access code, which caches the data in a netsnmp-
    container (usually a sorted array).

    Available options can be determined by checking for mib2c configuration
    files that begin with 'mfd-access-*'.

    Syntax: @eval $m2c_table_access = 'container-cached'@

 
    m2c_include_examples (currently '1')
    ------------------------------------------------------------------
    This variable determines whether or not to generate example code. The
    default is to generate example code.

    Syntax: @eval $m2c_include_examples = 0@


    m2c_data_transient (currently '2')
    ------------------------------------------------------------------
    This variable determines how the generated example code deals with the
    data during data lookup. See the table readme file for details on how
    the current table access method interprets this value. In general,
    a value of 0 indicates persistent data, 1 indicates semi-transient and
    2 indicates transient data.

    Syntax: @eval $m2c_data_transient = 0@


 Index(es) for the trafficProcessorTable table
  ------------------------------------------------------------
  The index(es) for the trafficProcessorTable table are:

     trafficProcessorIndex:
        Syntax:      INTEGER32
        DataType:    INTEGER32
        ASN type:    ASN_INTEGER
        C-code type: long

  You should know how to set all these values from your data context,
  trafficProcessorTable_data.


************************************************************************
trafficProcessorTable File Overview
------------------------------------------------------------------------
  Several files have been generated to implement the trafficProcessorTable
  table. We'll go through these files, one by one, explaining each and
  letting you know which you need to edit.


File: trafficProcessorTable_data_access.[c|h]
------------------------------------------------------------------------
  The trafficProcessorTable_data_access file contains the interface to your data in
  its raw format.  These functions are used to build the row cache or 
  locate the row (depending on the table access method).

  Set MIB context
  -----------------
  TODO : Set MIB index values
  FUNC : trafficProcessorTable_indexes_set
  WHERE: trafficProcessorTable_data_access.c

  This is a convenience function for setting the index context from
  the native C data. Where necessary, value mapping should be done.

  This function should update the table index values (found in
  tbl_idx) for the given raw data.

  
  container summary
  ------------------------
    The container data access code is for cases when you want to
    store your data in the agent/sub-agent.

    ... to be continued...


  cache summary
  ------------------------
    The container-cached data access code is for cases when you want to
    cache your data in the agent/sub-agent.

    ... to be continued...




File: trafficProcessorTable_enums.h
------------------------------------------------------------------------
  This file contains macros for mapping enumeration values when the
  enumerated values defined by the MIB do not match the values used
  internally.

  Review this file to see if any values need to be updated.


File: trafficProcessorTable_data_get.c
------------------------------------------------------------------------
  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineFramerFsmmtrb3s_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineFramerFsmmtrb2s_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineFramerFsmmtrb1s_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineFramerFsmms_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineFramerSif_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineFramerSoof_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineFramerSlof_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineLosstatLosf_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineSecmonFlom_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineSecmonBipsfs_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineSecmonDiae_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineSecmonDbdi_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : lineSecmonLom_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : linePathmonAccstat_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : linePathmonMsiunst_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : linePathmonDais_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : linePathmonDlck_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : linePathmonDbdi_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1FramerFsmms_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1FramerFssusts_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1FramerSif_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1FramerSoof_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1FramerSlof_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1FramerFst_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1LosstatLosf_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1SecmonFlom_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1SecmonBipsfs_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1SecmonDiae_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1SecmonDbdi_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1SecmonLom_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1PathmonAccstat_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1PathmonMsiunst_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1PathmonDais_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1PathmonDlck_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client1PathmonDbdi_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2FramerFsmms_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2FramerFssusts_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2FramerSif_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2FramerSoof_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2FramerSlof_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2FramerFst_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2LosstatLosf_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2SecmonFlom_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2SecmonBipsfs_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2SecmonDiae_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2SecmonDbdi_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2SecmonLom_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2PathmonAccstat_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2PathmonMsiunst_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2PathmonDais_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2PathmonDlck_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client2PathmonDbdi_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3FramerFsmms_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3FramerFssusts_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3FramerSif_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3FramerSoof_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3FramerSlof_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3FramerFst_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3LosstatLosf_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3SecmonFlom_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3SecmonBipsfs_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3SecmonDiae_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3SecmonDbdi_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3SecmonLom_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3PathmonAccstat_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3PathmonMsiunst_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3PathmonDais_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3PathmonDlck_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client3PathmonDbdi_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4FramerFsmms_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4FramerFssusts_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4FramerSif_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4FramerSoof_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4FramerSlof_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4FramerFst_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4LosstatLosf_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4SecmonFlom_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4SecmonBipsfs_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4SecmonDiae_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4SecmonDbdi_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4SecmonLom_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4PathmonAccstat_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4PathmonMsiunst_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4PathmonDais_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4PathmonDlck_get

  Get data for column
  -------------------
  TODO : retrieve column data from raw data
  FUNC : client4PathmonDbdi_get



File: trafficProcessorTable_data_set.c
------------------------------------------------------------------------

  This table does not support set requests.


************************************************************************
trafficProcessorTable Reference
------------------------------------------------------------------------

Function flow
----------------------------------------------------
To give you the general idea of how the functions flow works, this
example flow is from a complete table implementation.

NOTE: Depending on your configuration, some of the functions used in the
      examples below  may not have been generated for the
      trafficProcessorTable table.

      Conversely, the examples below may not include some functions that
      were generated for the trafficProcessorTable table.

To watch the flow of the trafficProcessorTable table, use the
following debug tokens:

        snmp_agent
        helper:table:req
        trafficProcessorTable
        verbose:trafficProcessorTable
        internal:trafficProcessorTable

e.g.
        snmpd -f -Le -DtrafficProcessorTable,verbose:trafficProcessorTable,internal:trafficProcessorTable


Initialization
--------------------------------
init_xxxTable: called                           xxx.c
   initialize_table_xxxTable                    xxx.c
      _xxxTable_initialize_interface            xxx_interface.c
         xxxTable_init_data                     xxx_data_access.c
      _xxxTable_container_init                  xxx_interface.c
         xxxTable_container_init                xxx_data_access.c


GET Request
--------------------------------
_cache_load                                     xxx_interface.c
   xxxTable_cache_load                          xxx_data_access.c
      xxxTable_allocate_rowreq_ctx              xxx_interface.c
         xxxTable_allocate_data                 xxx_data_get.c
         xxxTable_rowreq_ctx_init               xxx_data_get.c
      xxxTable_indexes_set                      xxx_data_get.c
         xxxTable_indexes_set_tbl_idx           xxx_data_get.c

xxxTable_pre_request                              

_mfd_xxxTable_object_lookup                     xxx_interface.c
   xxxTable_row_prep                            xxx_data_access.c

_mfd_xxxTable_get_values                        xxx_interface.c
   _mfd_xxxTable_get_column                     xxx_interface.c
      yyy_get                                   xxx_data_get.c

xxxTable_post_request


GETNEXT Request
--------------------------------
_cache_load                                     ...
xxxTable_pre_request                            ...
_mfd_xxxTable_object_lookup                     ...
_mfd_xxxTable_get_values                        ...
xxxTable_post_request                           ...


SET Request: success
--------------------------------
_cache_load                                     ...
xxxTable_pre_request
_mfd_xxxTable_object_lookup                     ...

_mfd_xxxTable_check_objects                     xxx_interface.c
   _xxxTable_check_column                       xxx_interface.c
      yyy_check_value                           xxx_data_set.c

_mfd_xxxTable_undo_setup                        xxx_interface.c
   xxxTable_allocate_data                       ...
   xxxTable_undo_setup                          xxx_interface.c
      _xxxTable_undo_setup_column               xxx_interface.c
         yyy_undo_setup                         xxx_data_set.c

_mfd_xxxTable_set_values                        xxx_interface.c
   _xxxTable_set_column                         xxx_interface.c
      yyy_set                                   xxx_data_set.c

_mfd_xxxTable_check_dependencies                xxx_interface.c
   xxxTable_check_dependencies                  xxx_data_set.c

_mfd_xxxTable_commit                            xxx_interface.c
   xxxTable_commit                              xxx_data_set.c

_mfd_xxxTable_undo_cleanup                      xxx_interface.c
   xxxTable_undo_cleanup                        xxx_data_set.c
      xxxTable_release_data                     ...

xxxTable_post_request                           ...


SET Request: row creation
--------------------------------
_cache_load                                     ...
xxxTable_pre_request

_mfd_xxxTable_object_lookup                     ...
   xxxTable_index_from_oid                      xxx_interface.c
   xxxTable_allocate_rowreq_ctx                 ...
      ...
   _xxxTable_check_indexes                      xxx_interface.c
      yyy_check_index                           xxx_data_set.c
      xxxTable_validate_index                   xxx_data_set.c

_mfd_xxxTable_check_objects                     ...
   _xxxTable_check_column                       ...
      yyy_check_value                           ...
   _xxxTable_check_column                       ...
      yyy_check_value                           ...

_mfd_xxxTable_undo_setup                        ...
_mfd_xxxTable_set_values                        ...
_mfd_xxxTable_check_dependencies                ...
_mfd_xxxTable_commit                            ...
_mfd_xxxTable_undo_cleanup                      ...
xxxTable_post_request                           ...


SET Resuest: value error
--------------------------------
_cache_load                                     ...
xxxTable_pre_request                            ...
_mfd_xxxTable_object_lookup                     ...

_mfd_xxxTable_check_objects                     ...
   _xxxTable_check_column                       ...
      yyy_check_value                           ...
      ERROR:"yyy value not supported"

xxxTable_post_request                           ...


SET Request: commit failure
--------------------------------
_cache_load                                     ...
xxxTable_pre_request                            ...
_mfd_xxxTable_object_lookup                     ...
_mfd_xxxTable_check_objects                     ...
_mfd_xxxTable_undo_setup                        ...
_mfd_xxxTable_set_values                        ...
_mfd_xxxTable_check_dependencies                ...

_mfd_xxxTable_commit                            ...
   xxxTable_commit                              ...
   ERROR: bad rc -1

_mfd_xxxTable_undo_commit                       xxx_interface.c
   xxxTable_undo_commit                         xxx_data_set.c

_mfd_xxxTable_undo_values                       xxx_interface.c
   _xxxTable_undo_column                        xxx_interface.c
      yyy_undo                                  xxx_data_set.c

_mfd_xxxTable_undo_cleanup                      ...
xxxTable_post_request                           ...


Row release (user initiated)
--------------------------------
xxxTable_release_rowreq_ctx                     xxx_interface.c
   xxxTable_rowreq_ctx_cleanup                  xxx_data_get.c
   xxxTable_release_data                        xxx_data_get.c



Table / column details
----------------------------------------------------
/**********************************************************************
 **********************************************************************
 ***
 *** Table trafficProcessorTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * FTNC-MIB::trafficProcessorTable is subid 1 of trafficProcessor.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1, length: 13
*/

/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.trafficProcessorIndex
 * trafficProcessorIndex is subid 1 of trafficProcessorEntry.
 * Its status is Current, and its access level is NoAccess.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.1
 * Description:
The auxiliary variable used for identifying instances
            of the columnar objects in the txpSeverityTable
 *
 * Attributes:
 *   accessible 0     isscalar 0     enums  0      hasdefval 0
 *   readable   0     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 65535;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 *
 *
 *
 * NOTE: NODE trafficProcessorIndex IS NOT ACCESSIBLE
 *
 *
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineFramerFsmmtrb3s
 * lineFramerFsmmtrb3s is subid 2 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.2
 * Description:
Line Framer FS mismatch for tributary 3
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineFramerFsmmtrb2s
 * lineFramerFsmmtrb2s is subid 3 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.3
 * Description:
Line Framer FS mismatch for tributary 2
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineFramerFsmmtrb1s
 * lineFramerFsmmtrb1s is subid 4 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.4
 * Description:
Line Framer FS mismatch for tributary 1
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineFramerFsmms
 * lineFramerFsmms is subid 5 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.5
 * Description:
Line Framer FS timeslot for FS mismatch
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineFramerSif
 * lineFramerSif is subid 6 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.6
 * Description:
Line Framer SIF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineFramerSoof
 * lineFramerSoof is subid 7 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.7
 * Description:
Line Framer OOF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineFramerSlof
 * lineFramerSlof is subid 8 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.8
 * Description:
Line Framer LOF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineLosstatLosf
 * lineLosstatLosf is subid 9 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.9
 * Description:
Line LOS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineSecmonFlom
 * lineSecmonFlom is subid 10 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.10
 * Description:
Line Section LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineSecmonBipsfs
 * lineSecmonBipsfs is subid 11 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.11
 * Description:
Line Section BIPSFS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineSecmonDiae
 * lineSecmonDiae is subid 12 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.12
 * Description:
Line Section DIAE status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineSecmonDbdi
 * lineSecmonDbdi is subid 13 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.13
 * Description:
Line Section DBDI status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.lineSecmonLom
 * lineSecmonLom is subid 14 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.14
 * Description:
Line Path LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.linePathmonAccstat
 * linePathmonAccstat is subid 15 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.15
 * Description:
Line Path LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.linePathmonMsiunst
 * linePathmonMsiunst is subid 16 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.16
 * Description:
Line Path MSIUNST status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.linePathmonDais
 * linePathmonDais is subid 17 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.17
 * Description:
Line Path DAIS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.linePathmonDlck
 * linePathmonDlck is subid 18 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.18
 * Description:
Line Path DLCK status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.linePathmonDbdi
 * linePathmonDbdi is subid 19 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.19
 * Description:
Line Path DLCK status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1FramerFsmms
 * client1FramerFsmms is subid 20 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.20
 * Description:
Client 1 FS mismatch
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1FramerFssusts
 * client1FramerFssusts is subid 21 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.21
 * Description:
Client 1 FS unstable
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1FramerSif
 * client1FramerSif is subid 22 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.22
 * Description:
Client1 Framer SIF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1FramerSoof
 * client1FramerSoof is subid 23 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.23
 * Description:
Client1 Framer OOF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1FramerSlof
 * client1FramerSlof is subid 24 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.24
 * Description:
Client1 Framer LOF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1FramerFst
 * client1FramerFst is subid 25 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.25
 * Description:
Client1 Framer FST status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1LosstatLosf
 * client1LosstatLosf is subid 26 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.26
 * Description:
Client1 LOS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1SecmonFlom
 * client1SecmonFlom is subid 27 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.27
 * Description:
Client1 Section LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1SecmonBipsfs
 * client1SecmonBipsfs is subid 28 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.28
 * Description:
Client1 Section BIPSFS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1SecmonDiae
 * client1SecmonDiae is subid 29 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.29
 * Description:
Client1 Section DIAE status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1SecmonDbdi
 * client1SecmonDbdi is subid 30 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.30
 * Description:
Client1 Section DBDI status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1SecmonLom
 * client1SecmonLom is subid 31 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.31
 * Description:
Client1 Path LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1PathmonAccstat
 * client1PathmonAccstat is subid 32 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.32
 * Description:
Client1 Path LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1PathmonMsiunst
 * client1PathmonMsiunst is subid 33 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.33
 * Description:
Client1 Path MSIUNST status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1PathmonDais
 * client1PathmonDais is subid 34 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.34
 * Description:
Client1 Path DAIS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1PathmonDlck
 * client1PathmonDlck is subid 35 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.35
 * Description:
Client1 Path DLCK status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client1PathmonDbdi
 * client1PathmonDbdi is subid 36 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.36
 * Description:
Client1 Path DLCK status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2FramerFsmms
 * client2FramerFsmms is subid 37 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.37
 * Description:
Client 1 FS mismatch
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2FramerFssusts
 * client2FramerFssusts is subid 38 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.38
 * Description:
Client 1 FS unstable
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2FramerSif
 * client2FramerSif is subid 39 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.39
 * Description:
Client2 Framer SIF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2FramerSoof
 * client2FramerSoof is subid 40 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.40
 * Description:
Client2 Framer OOF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2FramerSlof
 * client2FramerSlof is subid 41 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.41
 * Description:
Client2 Framer LOF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2FramerFst
 * client2FramerFst is subid 42 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.42
 * Description:
Client2 Framer FST status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2LosstatLosf
 * client2LosstatLosf is subid 43 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.43
 * Description:
Client2 LOS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2SecmonFlom
 * client2SecmonFlom is subid 44 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.44
 * Description:
Client2 Section LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2SecmonBipsfs
 * client2SecmonBipsfs is subid 45 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.45
 * Description:
Client2 Section BIPSFS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2SecmonDiae
 * client2SecmonDiae is subid 46 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.46
 * Description:
Client2 Section DIAE status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2SecmonDbdi
 * client2SecmonDbdi is subid 47 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.47
 * Description:
Client2 Section DBDI status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2SecmonLom
 * client2SecmonLom is subid 48 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.48
 * Description:
Client2 Path LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2PathmonAccstat
 * client2PathmonAccstat is subid 49 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.49
 * Description:
Client2 Path LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2PathmonMsiunst
 * client2PathmonMsiunst is subid 50 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.50
 * Description:
Client2 Path MSIUNST status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2PathmonDais
 * client2PathmonDais is subid 51 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.51
 * Description:
Client2 Path DAIS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2PathmonDlck
 * client2PathmonDlck is subid 52 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.52
 * Description:
Client2 Path DLCK status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client2PathmonDbdi
 * client2PathmonDbdi is subid 53 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.53
 * Description:
Client2 Path DLCK status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3FramerFsmms
 * client3FramerFsmms is subid 54 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.54
 * Description:
Client 1 FS mismatch
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3FramerFssusts
 * client3FramerFssusts is subid 55 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.55
 * Description:
Client 1 FS unstable
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3FramerSif
 * client3FramerSif is subid 56 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.56
 * Description:
Client3 Framer SIF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3FramerSoof
 * client3FramerSoof is subid 57 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.57
 * Description:
Client3 Framer OOF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3FramerSlof
 * client3FramerSlof is subid 58 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.58
 * Description:
Client3 Framer LOF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3FramerFst
 * client3FramerFst is subid 59 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.59
 * Description:
Client3 Framer FST status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3LosstatLosf
 * client3LosstatLosf is subid 60 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.60
 * Description:
Client3 LOS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3SecmonFlom
 * client3SecmonFlom is subid 61 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.61
 * Description:
Client3 Section LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3SecmonBipsfs
 * client3SecmonBipsfs is subid 62 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.62
 * Description:
Client3 Section BIPSFS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3SecmonDiae
 * client3SecmonDiae is subid 63 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.63
 * Description:
Client3 Section DIAE status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3SecmonDbdi
 * client3SecmonDbdi is subid 64 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.64
 * Description:
Client3 Section DBDI status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3SecmonLom
 * client3SecmonLom is subid 65 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.65
 * Description:
Client3 Path LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3PathmonAccstat
 * client3PathmonAccstat is subid 66 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.66
 * Description:
Client3 Path LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3PathmonMsiunst
 * client3PathmonMsiunst is subid 67 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.67
 * Description:
Client3 Path MSIUNST status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3PathmonDais
 * client3PathmonDais is subid 68 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.68
 * Description:
Client3 Path DAIS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3PathmonDlck
 * client3PathmonDlck is subid 69 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.69
 * Description:
Client3 Path DLCK status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client3PathmonDbdi
 * client3PathmonDbdi is subid 70 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.70
 * Description:
Client3 Path DLCK status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4FramerFsmms
 * client4FramerFsmms is subid 71 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.71
 * Description:
Client 1 FS mismatch
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4FramerFssusts
 * client4FramerFssusts is subid 72 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.72
 * Description:
Client 1 FS unstable
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4FramerSif
 * client4FramerSif is subid 73 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.73
 * Description:
Client4 Framer SIF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4FramerSoof
 * client4FramerSoof is subid 74 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.74
 * Description:
Client4 Framer OOF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4FramerSlof
 * client4FramerSlof is subid 75 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.75
 * Description:
Client4 Framer LOF status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4FramerFst
 * client4FramerFst is subid 76 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.76
 * Description:
Client4 Framer FST status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4LosstatLosf
 * client4LosstatLosf is subid 77 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.77
 * Description:
Client4 LOS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4SecmonFlom
 * client4SecmonFlom is subid 78 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.78
 * Description:
Client4 Section LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4SecmonBipsfs
 * client4SecmonBipsfs is subid 79 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.79
 * Description:
Client4 Section BIPSFS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4SecmonDiae
 * client4SecmonDiae is subid 80 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.80
 * Description:
Client4 Section DIAE status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4SecmonDbdi
 * client4SecmonDbdi is subid 81 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.81
 * Description:
Client4 Section DBDI status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4SecmonLom
 * client4SecmonLom is subid 82 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.82
 * Description:
Client4 Path LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4PathmonAccstat
 * client4PathmonAccstat is subid 83 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.83
 * Description:
Client4 Path LOM status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4PathmonMsiunst
 * client4PathmonMsiunst is subid 84 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.84
 * Description:
Client4 Path MSIUNST status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4PathmonDais
 * client4PathmonDais is subid 85 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.85
 * Description:
Client4 Path DAIS status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4PathmonDlck
 * client4PathmonDlck is subid 86 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.86
 * Description:
Client4 Path DLCK status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/*---------------------------------------------------------------------
 * FTNC-MIB::trafficProcessorEntry.client4PathmonDbdi
 * client4PathmonDbdi is subid 87 of trafficProcessorEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.10.1.1.87
 * Description:
Client4 Path DLCK status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */


