/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "../../txpDSPCompensationTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement txpDSPCompensationTable get routines.
 * TODO:240:M: Implement txpDSPCompensationTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table txpDSPCompensationTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * FTNC-MIB::txpDSPCompensationTable is subid 3 of txpDSP.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.43484.2.9.3.3, length: 11
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement txpDSPCompensationTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param txpDSPCompensationIndex_ptr
 * @param txpDSPCompensationIndex_ptr_len
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
txpDSPCompensationTable_indexes_set_tbl_idx(txpDSPCompensationTable_mib_index *tbl_idx, char *txpDSPCompensationIndex_val_ptr,  size_t txpDSPCompensationIndex_val_ptr_len)
{
    DEBUGMSGTL(("verbose:txpDSPCompensationTable:txpDSPCompensationTable_indexes_set_tbl_idx","called\n"));

    /* txpDSPCompensationIndex(1)/OCTETSTR/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h */
    tbl_idx->txpDSPCompensationIndex_len = sizeof(tbl_idx->txpDSPCompensationIndex)/sizeof(tbl_idx->txpDSPCompensationIndex[0]); /* max length */
    /*
     * make sure there is enough space for txpDSPCompensationIndex data
     */
    if ((NULL == tbl_idx->txpDSPCompensationIndex) ||
        (tbl_idx->txpDSPCompensationIndex_len <
         (txpDSPCompensationIndex_val_ptr_len))) {
        snmp_log(LOG_ERR,"not enough space for value (txpDSPCompensationIndex_val_ptr)\n");
        return MFD_ERROR;
    }
    tbl_idx->txpDSPCompensationIndex_len = txpDSPCompensationIndex_val_ptr_len;
    memcpy( tbl_idx->txpDSPCompensationIndex, txpDSPCompensationIndex_val_ptr, txpDSPCompensationIndex_val_ptr_len* sizeof(txpDSPCompensationIndex_val_ptr[0]) );
    

    return MFD_SUCCESS;
} /* txpDSPCompensationTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
txpDSPCompensationTable_indexes_set(txpDSPCompensationTable_rowreq_ctx *rowreq_ctx, char *txpDSPCompensationIndex_val_ptr,  size_t txpDSPCompensationIndex_val_ptr_len)
{
    DEBUGMSGTL(("verbose:txpDSPCompensationTable:txpDSPCompensationTable_indexes_set","called\n"));

    if(MFD_SUCCESS != txpDSPCompensationTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , txpDSPCompensationIndex_val_ptr, txpDSPCompensationIndex_val_ptr_len
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != txpDSPCompensationTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* txpDSPCompensationTable_indexes_set */


/*---------------------------------------------------------------------
 * FTNC-MIB::txpDSPCompensationEntry.minBulkCDCompensation
 * minBulkCDCompensation is subid 2 of txpDSPCompensationEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.43484.2.9.3.3.1.2
 * Description:
txp40G DSP Minimum bulk CD Compensation.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the minBulkCDCompensation data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param minBulkCDCompensation_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param minBulkCDCompensation_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by minBulkCDCompensation.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*minBulkCDCompensation_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update minBulkCDCompensation_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
minBulkCDCompensation_get( txpDSPCompensationTable_rowreq_ctx *rowreq_ctx, char **minBulkCDCompensation_val_ptr_ptr, size_t *minBulkCDCompensation_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != minBulkCDCompensation_val_ptr_ptr) && (NULL != *minBulkCDCompensation_val_ptr_ptr));
   netsnmp_assert( NULL != minBulkCDCompensation_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:txpDSPCompensationTable:minBulkCDCompensation_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the minBulkCDCompensation data.
 * copy (* minBulkCDCompensation_val_ptr_ptr ) data and (* minBulkCDCompensation_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for minBulkCDCompensation data
     */
    if ((NULL == (* minBulkCDCompensation_val_ptr_ptr )) ||
        ((* minBulkCDCompensation_val_ptr_len_ptr ) <
         (rowreq_ctx->data.minBulkCDCompensation_len* sizeof(rowreq_ctx->data.minBulkCDCompensation[0])))) {
        /*
         * allocate space for minBulkCDCompensation data
         */
        (* minBulkCDCompensation_val_ptr_ptr ) = malloc(rowreq_ctx->data.minBulkCDCompensation_len* sizeof(rowreq_ctx->data.minBulkCDCompensation[0]));
        if(NULL == (* minBulkCDCompensation_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.minBulkCDCompensation)\n");
            return MFD_ERROR;
        }
    }
    (* minBulkCDCompensation_val_ptr_len_ptr ) = rowreq_ctx->data.minBulkCDCompensation_len* sizeof(rowreq_ctx->data.minBulkCDCompensation[0]);
    memcpy( (* minBulkCDCompensation_val_ptr_ptr ), rowreq_ctx->data.minBulkCDCompensation, rowreq_ctx->data.minBulkCDCompensation_len* sizeof(rowreq_ctx->data.minBulkCDCompensation[0]) );

    return MFD_SUCCESS;
} /* minBulkCDCompensation_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::txpDSPCompensationEntry.maxBulkCDCompensation
 * maxBulkCDCompensation is subid 3 of txpDSPCompensationEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.43484.2.9.3.3.1.3
 * Description:
txp40G DSP Maximum bulk CD Compensation.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the maxBulkCDCompensation data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param maxBulkCDCompensation_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param maxBulkCDCompensation_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by maxBulkCDCompensation.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*maxBulkCDCompensation_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update maxBulkCDCompensation_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
maxBulkCDCompensation_get( txpDSPCompensationTable_rowreq_ctx *rowreq_ctx, char **maxBulkCDCompensation_val_ptr_ptr, size_t *maxBulkCDCompensation_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != maxBulkCDCompensation_val_ptr_ptr) && (NULL != *maxBulkCDCompensation_val_ptr_ptr));
   netsnmp_assert( NULL != maxBulkCDCompensation_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:txpDSPCompensationTable:maxBulkCDCompensation_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the maxBulkCDCompensation data.
 * copy (* maxBulkCDCompensation_val_ptr_ptr ) data and (* maxBulkCDCompensation_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for maxBulkCDCompensation data
     */
    if ((NULL == (* maxBulkCDCompensation_val_ptr_ptr )) ||
        ((* maxBulkCDCompensation_val_ptr_len_ptr ) <
         (rowreq_ctx->data.maxBulkCDCompensation_len* sizeof(rowreq_ctx->data.maxBulkCDCompensation[0])))) {
        /*
         * allocate space for maxBulkCDCompensation data
         */
        (* maxBulkCDCompensation_val_ptr_ptr ) = malloc(rowreq_ctx->data.maxBulkCDCompensation_len* sizeof(rowreq_ctx->data.maxBulkCDCompensation[0]));
        if(NULL == (* maxBulkCDCompensation_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.maxBulkCDCompensation)\n");
            return MFD_ERROR;
        }
    }
    (* maxBulkCDCompensation_val_ptr_len_ptr ) = rowreq_ctx->data.maxBulkCDCompensation_len* sizeof(rowreq_ctx->data.maxBulkCDCompensation[0]);
    memcpy( (* maxBulkCDCompensation_val_ptr_ptr ), rowreq_ctx->data.maxBulkCDCompensation, rowreq_ctx->data.maxBulkCDCompensation_len* sizeof(rowreq_ctx->data.maxBulkCDCompensation[0]) );

    return MFD_SUCCESS;
} /* maxBulkCDCompensation_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::txpDSPCompensationEntry.stepSize
 * stepSize is subid 4 of txpDSPCompensationEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.43484.2.9.3.3.1.4
 * Description:
txp40G DSP Bulk CD step size.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the stepSize data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param stepSize_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param stepSize_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by stepSize.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*stepSize_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update stepSize_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
stepSize_get( txpDSPCompensationTable_rowreq_ctx *rowreq_ctx, char **stepSize_val_ptr_ptr, size_t *stepSize_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != stepSize_val_ptr_ptr) && (NULL != *stepSize_val_ptr_ptr));
   netsnmp_assert( NULL != stepSize_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:txpDSPCompensationTable:stepSize_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the stepSize data.
 * copy (* stepSize_val_ptr_ptr ) data and (* stepSize_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for stepSize data
     */
    if ((NULL == (* stepSize_val_ptr_ptr )) ||
        ((* stepSize_val_ptr_len_ptr ) <
         (rowreq_ctx->data.stepSize_len* sizeof(rowreq_ctx->data.stepSize[0])))) {
        /*
         * allocate space for stepSize data
         */
        (* stepSize_val_ptr_ptr ) = malloc(rowreq_ctx->data.stepSize_len* sizeof(rowreq_ctx->data.stepSize[0]));
        if(NULL == (* stepSize_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.stepSize)\n");
            return MFD_ERROR;
        }
    }
    (* stepSize_val_ptr_len_ptr ) = rowreq_ctx->data.stepSize_len* sizeof(rowreq_ctx->data.stepSize[0]);
    memcpy( (* stepSize_val_ptr_ptr ), rowreq_ctx->data.stepSize, rowreq_ctx->data.stepSize_len* sizeof(rowreq_ctx->data.stepSize[0]) );

    return MFD_SUCCESS;
} /* stepSize_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::txpDSPCompensationEntry.cdCompensation
 * cdCompensation is subid 5 of txpDSPCompensationEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.43484.2.9.3.3.1.5
 * Description:
txp40G DSP Chromatic Dispersion Compensation.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the cdCompensation data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cdCompensation_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param cdCompensation_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by cdCompensation.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*cdCompensation_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update cdCompensation_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
cdCompensation_get( txpDSPCompensationTable_rowreq_ctx *rowreq_ctx, char **cdCompensation_val_ptr_ptr, size_t *cdCompensation_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != cdCompensation_val_ptr_ptr) && (NULL != *cdCompensation_val_ptr_ptr));
   netsnmp_assert( NULL != cdCompensation_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:txpDSPCompensationTable:cdCompensation_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the cdCompensation data.
 * copy (* cdCompensation_val_ptr_ptr ) data and (* cdCompensation_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for cdCompensation data
     */
    if ((NULL == (* cdCompensation_val_ptr_ptr )) ||
        ((* cdCompensation_val_ptr_len_ptr ) <
         (rowreq_ctx->data.cdCompensation_len* sizeof(rowreq_ctx->data.cdCompensation[0])))) {
        /*
         * allocate space for cdCompensation data
         */
        (* cdCompensation_val_ptr_ptr ) = malloc(rowreq_ctx->data.cdCompensation_len* sizeof(rowreq_ctx->data.cdCompensation[0]));
        if(NULL == (* cdCompensation_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.cdCompensation)\n");
            return MFD_ERROR;
        }
    }
    (* cdCompensation_val_ptr_len_ptr ) = rowreq_ctx->data.cdCompensation_len* sizeof(rowreq_ctx->data.cdCompensation[0]);
    memcpy( (* cdCompensation_val_ptr_ptr ), rowreq_ctx->data.cdCompensation, rowreq_ctx->data.cdCompensation_len* sizeof(rowreq_ctx->data.cdCompensation[0]) );

    return MFD_SUCCESS;
} /* cdCompensation_get */



/** @} */
