/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef EDFATABLE_H
#define EDFATABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(FTNC-MIB)
config_require(FTNC-MIB/edfaTable/edfaTable_interface)
config_require(FTNC-MIB/edfaTable/edfaTable_data_access)
config_require(FTNC-MIB/edfaTable/edfaTable_data_get)
config_require(FTNC-MIB/edfaTable/edfaTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for edfaTable */
#include "FTNC-MIB/edfaTable/edfaTable_oids.h"

/* enum definions */
#include "FTNC-MIB/edfaTable/edfaTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_edfaTable(void);
void shutdown_edfaTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table edfaTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * FTNC-MIB::edfaTable is subid 8 of mxpConfigMIBObjects.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.8, length: 12
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review edfaTable registration context.
     */
typedef netsnmp_data_list edfaTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review edfaTable data context structure.
 * This structure is used to represent the data for edfaTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * edfaTable.
 */
typedef struct edfaTable_data_s {
    
        /*
         * edfaPout(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   edfaPout[65535];
size_t      edfaPout_len; /* # of char elements, not bytes */
    
        /*
         * edfaPin(3)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   edfaPin[65535];
size_t      edfaPin_len; /* # of char elements, not bytes */
    
        /*
         * edfaLos(4)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   edfaLos[65535];
size_t      edfaLos_len; /* # of char elements, not bytes */
    
        /*
         * edfaLop(5)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   edfaLop[65535];
size_t      edfaLop_len; /* # of char elements, not bytes */
    
        /*
         * edfaAmpStat(6)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   edfaAmpStat[65535];
size_t      edfaAmpStat_len; /* # of char elements, not bytes */
    
} edfaTable_data;


/*
 * TODO:120:r: |-> Review edfaTable mib index.
 * This structure is used to represent the index for edfaTable.
 */
typedef struct edfaTable_mib_index_s {

        /*
         * edfaIndex(1)/OCTETSTR/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h
         */
   char   edfaIndex[32];
   size_t      edfaIndex_len;


} edfaTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review edfaTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
     *
     * BE VERY CAREFUL TO TAKE INTO ACCOUNT THE MAXIMUM
     * POSSIBLE LENGHT FOR EVERY VARIABLE LENGTH INDEX!
     * Guessing 128 - col/entry(2)  - oid len(12)
*/
#define MAX_edfaTable_IDX_LEN     33


/* *********************************************************************
 * TODO:130:o: |-> Review edfaTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * edfaTable_rowreq_ctx pointer.
 */
typedef struct edfaTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_edfaTable_IDX_LEN];
    
    edfaTable_mib_index        tbl_idx;
    
    edfaTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to edfaTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *edfaTable_data_list;

} edfaTable_rowreq_ctx;

typedef struct edfaTable_ref_rowreq_ctx_s {
    edfaTable_rowreq_ctx *rowreq_ctx;
} edfaTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int edfaTable_pre_request(edfaTable_registration * user_context);
    int edfaTable_post_request(edfaTable_registration * user_context,
        int rc);

    int edfaTable_rowreq_ctx_init(edfaTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void edfaTable_rowreq_ctx_cleanup(edfaTable_rowreq_ctx *rowreq_ctx);


    edfaTable_rowreq_ctx *
                  edfaTable_row_find_by_mib_index(edfaTable_mib_index *mib_idx);

extern const oid edfaTable_oid[];
extern const int edfaTable_oid_size;


#include "FTNC-MIB/edfaTable/edfaTable_interface.h"
#include "FTNC-MIB/edfaTable/edfaTable_data_access.h"
#include "FTNC-MIB/edfaTable/edfaTable_data_get.h"
#include "FTNC-MIB/edfaTable/edfaTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* EDFATABLE_H */
/** @} */
