/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for txpPowSupplyAlrmTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "txpPowSupplyAlrmTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "FTNC-MIB/txpPowSupplyAlrmTable/txpPowSupplyAlrmTable_interface.h"

const oid txpPowSupplyAlrmTable_oid[] = { TXPPOWSUPPLYALRMTABLE_OID };
const int txpPowSupplyAlrmTable_oid_size = OID_LENGTH(txpPowSupplyAlrmTable_oid);

    txpPowSupplyAlrmTable_registration  txpPowSupplyAlrmTable_user_context;

void initialize_table_txpPowSupplyAlrmTable(void);
void shutdown_table_txpPowSupplyAlrmTable(void);


/**
 * Initializes the txpPowSupplyAlrmTable module
 */
void
init_txpPowSupplyAlrmTable(void)
{
    DEBUGMSGTL(("verbose:txpPowSupplyAlrmTable:init_txpPowSupplyAlrmTable","called\n"));

    /*
     * TODO:300:o: Perform txpPowSupplyAlrmTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("txpPowSupplyAlrmTable"))
        initialize_table_txpPowSupplyAlrmTable();

} /* init_txpPowSupplyAlrmTable */

/**
 * Shut-down the txpPowSupplyAlrmTable module (agent is exiting)
 */
void
shutdown_txpPowSupplyAlrmTable(void)
{
    if (should_init("txpPowSupplyAlrmTable"))
        shutdown_table_txpPowSupplyAlrmTable();

}

/**
 * Initialize the table txpPowSupplyAlrmTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_txpPowSupplyAlrmTable(void)
{
    txpPowSupplyAlrmTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:txpPowSupplyAlrmTable:initialize_table_txpPowSupplyAlrmTable","called\n"));

    /*
     * TODO:301:o: Perform txpPowSupplyAlrmTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize txpPowSupplyAlrmTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("txpPowSupplyAlrmTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _txpPowSupplyAlrmTable_initialize_interface(user_context, flags);
} /* initialize_table_txpPowSupplyAlrmTable */

/**
 * Shutdown the table txpPowSupplyAlrmTable 
 */
void
shutdown_table_txpPowSupplyAlrmTable(void)
{
    /*
     * call interface shutdown code
     */
    _txpPowSupplyAlrmTable_shutdown_interface(&txpPowSupplyAlrmTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
txpPowSupplyAlrmTable_rowreq_ctx_init(txpPowSupplyAlrmTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:txpPowSupplyAlrmTable:txpPowSupplyAlrmTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra txpPowSupplyAlrmTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* txpPowSupplyAlrmTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void txpPowSupplyAlrmTable_rowreq_ctx_cleanup(txpPowSupplyAlrmTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:txpPowSupplyAlrmTable:txpPowSupplyAlrmTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra txpPowSupplyAlrmTable rowreq cleanup.
     */
} /* txpPowSupplyAlrmTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
txpPowSupplyAlrmTable_pre_request(txpPowSupplyAlrmTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:txpPowSupplyAlrmTable:txpPowSupplyAlrmTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform txpPowSupplyAlrmTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* txpPowSupplyAlrmTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
txpPowSupplyAlrmTable_post_request(txpPowSupplyAlrmTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:txpPowSupplyAlrmTable:txpPowSupplyAlrmTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform txpPowSupplyAlrmTable post-request actions.
     */

    return MFD_SUCCESS;
} /* txpPowSupplyAlrmTable_post_request */


/** @{ */
