/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "../../txpChannelTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement txpChannelTable get routines.
 * TODO:240:M: Implement txpChannelTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table txpChannelTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * FTNC-MIB::txpChannelTable is subid 3 of txpMiscellaneous.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.43484.2.9.2.3, length: 11
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement txpChannelTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param txpChannelIndex_ptr
 * @param txpChannelIndex_ptr_len
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
txpChannelTable_indexes_set_tbl_idx(txpChannelTable_mib_index *tbl_idx, char *txpChannelIndex_val_ptr,  size_t txpChannelIndex_val_ptr_len)
{
    DEBUGMSGTL(("verbose:txpChannelTable:txpChannelTable_indexes_set_tbl_idx","called\n"));

    /* txpChannelIndex(1)/OCTETSTR/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h */
    tbl_idx->txpChannelIndex_len = sizeof(tbl_idx->txpChannelIndex)/sizeof(tbl_idx->txpChannelIndex[0]); /* max length */
    /*
     * make sure there is enough space for txpChannelIndex data
     */
    if ((NULL == tbl_idx->txpChannelIndex) ||
        (tbl_idx->txpChannelIndex_len <
         (txpChannelIndex_val_ptr_len))) {
        snmp_log(LOG_ERR,"not enough space for value (txpChannelIndex_val_ptr)\n");
        return MFD_ERROR;
    }
    tbl_idx->txpChannelIndex_len = txpChannelIndex_val_ptr_len;
    memcpy( tbl_idx->txpChannelIndex, txpChannelIndex_val_ptr, txpChannelIndex_val_ptr_len* sizeof(txpChannelIndex_val_ptr[0]) );
    

    return MFD_SUCCESS;
} /* txpChannelTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
txpChannelTable_indexes_set(txpChannelTable_rowreq_ctx *rowreq_ctx, char *txpChannelIndex_val_ptr,  size_t txpChannelIndex_val_ptr_len)
{
    DEBUGMSGTL(("verbose:txpChannelTable:txpChannelTable_indexes_set","called\n"));

    if(MFD_SUCCESS != txpChannelTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , txpChannelIndex_val_ptr, txpChannelIndex_val_ptr_len
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != txpChannelTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* txpChannelTable_indexes_set */


/*---------------------------------------------------------------------
 * FTNC-MIB::txpChannelEntry.txpTxLaserITUChannel
 * txpTxLaserITUChannel is subid 2 of txpChannelEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.43484.2.9.2.3.1.2
 * Description:
txp40G Tx laser ITU Channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the txpTxLaserITUChannel data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param txpTxLaserITUChannel_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param txpTxLaserITUChannel_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by txpTxLaserITUChannel.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*txpTxLaserITUChannel_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update txpTxLaserITUChannel_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
txpTxLaserITUChannel_get( txpChannelTable_rowreq_ctx *rowreq_ctx, char **txpTxLaserITUChannel_val_ptr_ptr, size_t *txpTxLaserITUChannel_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != txpTxLaserITUChannel_val_ptr_ptr) && (NULL != *txpTxLaserITUChannel_val_ptr_ptr));
   netsnmp_assert( NULL != txpTxLaserITUChannel_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:txpChannelTable:txpTxLaserITUChannel_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the txpTxLaserITUChannel data.
 * copy (* txpTxLaserITUChannel_val_ptr_ptr ) data and (* txpTxLaserITUChannel_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for txpTxLaserITUChannel data
     */
    if ((NULL == (* txpTxLaserITUChannel_val_ptr_ptr )) ||
        ((* txpTxLaserITUChannel_val_ptr_len_ptr ) <
         (rowreq_ctx->data.txpTxLaserITUChannel_len* sizeof(rowreq_ctx->data.txpTxLaserITUChannel[0])))) {
        /*
         * allocate space for txpTxLaserITUChannel data
         */
        (* txpTxLaserITUChannel_val_ptr_ptr ) = malloc(rowreq_ctx->data.txpTxLaserITUChannel_len* sizeof(rowreq_ctx->data.txpTxLaserITUChannel[0]));
        if(NULL == (* txpTxLaserITUChannel_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.txpTxLaserITUChannel)\n");
            return MFD_ERROR;
        }
    }
    (* txpTxLaserITUChannel_val_ptr_len_ptr ) = rowreq_ctx->data.txpTxLaserITUChannel_len* sizeof(rowreq_ctx->data.txpTxLaserITUChannel[0]);
    memcpy( (* txpTxLaserITUChannel_val_ptr_ptr ), rowreq_ctx->data.txpTxLaserITUChannel, rowreq_ctx->data.txpTxLaserITUChannel_len* sizeof(rowreq_ctx->data.txpTxLaserITUChannel[0]) );

    return MFD_SUCCESS;
} /* txpTxLaserITUChannel_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::txpChannelEntry.txpRxLaserITUChannel
 * txpRxLaserITUChannel is subid 3 of txpChannelEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.43484.2.9.2.3.1.3
 * Description:
txp40G Rx laser ITU Channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the txpRxLaserITUChannel data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param txpRxLaserITUChannel_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param txpRxLaserITUChannel_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by txpRxLaserITUChannel.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*txpRxLaserITUChannel_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update txpRxLaserITUChannel_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
txpRxLaserITUChannel_get( txpChannelTable_rowreq_ctx *rowreq_ctx, char **txpRxLaserITUChannel_val_ptr_ptr, size_t *txpRxLaserITUChannel_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != txpRxLaserITUChannel_val_ptr_ptr) && (NULL != *txpRxLaserITUChannel_val_ptr_ptr));
   netsnmp_assert( NULL != txpRxLaserITUChannel_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:txpChannelTable:txpRxLaserITUChannel_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the txpRxLaserITUChannel data.
 * copy (* txpRxLaserITUChannel_val_ptr_ptr ) data and (* txpRxLaserITUChannel_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for txpRxLaserITUChannel data
     */
    if ((NULL == (* txpRxLaserITUChannel_val_ptr_ptr )) ||
        ((* txpRxLaserITUChannel_val_ptr_len_ptr ) <
         (rowreq_ctx->data.txpRxLaserITUChannel_len* sizeof(rowreq_ctx->data.txpRxLaserITUChannel[0])))) {
        /*
         * allocate space for txpRxLaserITUChannel data
         */
        (* txpRxLaserITUChannel_val_ptr_ptr ) = malloc(rowreq_ctx->data.txpRxLaserITUChannel_len* sizeof(rowreq_ctx->data.txpRxLaserITUChannel[0]));
        if(NULL == (* txpRxLaserITUChannel_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.txpRxLaserITUChannel)\n");
            return MFD_ERROR;
        }
    }
    (* txpRxLaserITUChannel_val_ptr_len_ptr ) = rowreq_ctx->data.txpRxLaserITUChannel_len* sizeof(rowreq_ctx->data.txpRxLaserITUChannel[0]);
    memcpy( (* txpRxLaserITUChannel_val_ptr_ptr ), rowreq_ctx->data.txpRxLaserITUChannel, rowreq_ctx->data.txpRxLaserITUChannel_len* sizeof(rowreq_ctx->data.txpRxLaserITUChannel[0]) );

    return MFD_SUCCESS;
} /* txpRxLaserITUChannel_get */



/** @} */
