#ifndef __MXP_ERROR_H__
#define __MXP_ERROR_H__


/** GPIO ERROR's*/
#define GPIO_PORT_OUT_OF_RANGE_ERROR -4
#define GPIO_BASE_OR_LIMIT_OUT_OF_RANGE_ERROR -4
#define GPIO_OPEN_OPERATION_ERROR -4
#define GPIO_CLOSE_OPERATION_ERROR -4
#define GPIO_READ_OPERATION_ERROR -4
#define GPIO_WRITE_OPERATION_ERROR -4

/** I"C ERROR's */
#define I2C_READ_ERROR -5
#define I2C_WRITE_ERROR -6

#define XFP_I2C_BUS_NAME_OUT_OF_RANGE  -10
#define XFP_I2C_DATA_RATE_OUT_OF_RANGE -11
#define XFP_COMMUNICATION_DISABLED -12

#endif /* __UTIL_H__ */
