/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef TXPSEVERITYTABLE_DATA_ACCESS_H
#define TXPSEVERITYTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table txpSeverityTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * FTNC-MIB::txpSeverityTable is subid 1 of txpAlarms.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.43484.1.1.3.4.1, length: 12
*/

int txpSeverityTable_init_data(txpSeverityTable_registration * txpSeverityTable_reg);

    /*
     * TODO:180:o: Review txpSeverityTable cache timeout.
     * The number of seconds before the cache times out
     */
#define TXPSEVERITYTABLE_CACHE_TIMEOUT   1

void txpSeverityTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void txpSeverityTable_container_shutdown(netsnmp_container *container_ptr);

int txpSeverityTable_container_load(netsnmp_container *container);
void txpSeverityTable_container_free(netsnmp_container *container);

int txpSeverityTable_cache_load(netsnmp_container *container);
void txpSeverityTable_cache_free(netsnmp_container *container);

int txpSeverityTable_row_prep( txpSeverityTable_rowreq_ctx *rowreq_ctx);

#ifdef __cplusplus
}
#endif

#endif /* TXPSEVERITYTABLE_DATA_ACCESS_H */
