/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef TXPPOWSUPPLYALRMTABLE_H
#define TXPPOWSUPPLYALRMTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(FTNC-MIB)
config_require(FTNC-MIB/txpPowSupplyAlrmTable/txpPowSupplyAlrmTable_interface)
config_require(FTNC-MIB/txpPowSupplyAlrmTable/txpPowSupplyAlrmTable_data_access)
config_require(FTNC-MIB/txpPowSupplyAlrmTable/txpPowSupplyAlrmTable_data_get)
config_require(FTNC-MIB/txpPowSupplyAlrmTable/txpPowSupplyAlrmTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for txpPowSupplyAlrmTable */
#include "FTNC-MIB/txpPowSupplyAlrmTable/txpPowSupplyAlrmTable_oids.h"

/* enum definions */
#include "FTNC-MIB/txpPowSupplyAlrmTable/txpPowSupplyAlrmTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_txpPowSupplyAlrmTable(void);
void shutdown_txpPowSupplyAlrmTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table txpPowSupplyAlrmTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * FTNC-MIB::txpPowSupplyAlrmTable is subid 3 of txpAlrm.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.43484.2.9.1.3, length: 11
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review txpPowSupplyAlrmTable registration context.
     */
typedef netsnmp_data_list txpPowSupplyAlrmTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review txpPowSupplyAlrmTable data context structure.
 * This structure is used to represent the data for txpPowSupplyAlrmTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * txpPowSupplyAlrmTable.
 */
typedef struct txpPowSupplyAlrmTable_data_s {
    
        /*
         * txpPSUMMARY(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   txpPSUMMARY[65535];
size_t      txpPSUMMARY_len; /* # of char elements, not bytes */
    
        /*
         * txpP5VANALOG(3)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   txpP5VANALOG[65535];
size_t      txpP5VANALOG_len; /* # of char elements, not bytes */
    
        /*
         * txpN5V2ANALOG(4)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   txpN5V2ANALOG[65535];
size_t      txpN5V2ANALOG_len; /* # of char elements, not bytes */
    
        /*
         * txpP3P3VANALOG(5)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   txpP3P3VANALOG[65535];
size_t      txpP3P3VANALOG_len; /* # of char elements, not bytes */
    
        /*
         * txpP3P3VDIGITAL(6)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   txpP3P3VDIGITAL[65535];
size_t      txpP3P3VDIGITAL_len; /* # of char elements, not bytes */
    
        /*
         * txpLVDIGITAL(7)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   txpLVDIGITAL[65535];
size_t      txpLVDIGITAL_len; /* # of char elements, not bytes */
    
        /*
         * txpN5P2VDIGITAL(8)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   txpN5P2VDIGITAL[65535];
size_t      txpN5P2VDIGITAL_len; /* # of char elements, not bytes */
    
} txpPowSupplyAlrmTable_data;


/*
 * TODO:120:r: |-> Review txpPowSupplyAlrmTable mib index.
 * This structure is used to represent the index for txpPowSupplyAlrmTable.
 */
typedef struct txpPowSupplyAlrmTable_mib_index_s {

        /*
         * txpPowSupplyAlrmIndex(1)/OCTETSTR/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h
         */
   char   txpPowSupplyAlrmIndex[32];
   size_t      txpPowSupplyAlrmIndex_len;


} txpPowSupplyAlrmTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review txpPowSupplyAlrmTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
     *
     * BE VERY CAREFUL TO TAKE INTO ACCOUNT THE MAXIMUM
     * POSSIBLE LENGHT FOR EVERY VARIABLE LENGTH INDEX!
     * Guessing 128 - col/entry(2)  - oid len(11)
*/
#define MAX_txpPowSupplyAlrmTable_IDX_LEN     33


/* *********************************************************************
 * TODO:130:o: |-> Review txpPowSupplyAlrmTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * txpPowSupplyAlrmTable_rowreq_ctx pointer.
 */
typedef struct txpPowSupplyAlrmTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_txpPowSupplyAlrmTable_IDX_LEN];
    
    txpPowSupplyAlrmTable_mib_index        tbl_idx;
    
    txpPowSupplyAlrmTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to txpPowSupplyAlrmTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *txpPowSupplyAlrmTable_data_list;

} txpPowSupplyAlrmTable_rowreq_ctx;

typedef struct txpPowSupplyAlrmTable_ref_rowreq_ctx_s {
    txpPowSupplyAlrmTable_rowreq_ctx *rowreq_ctx;
} txpPowSupplyAlrmTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int txpPowSupplyAlrmTable_pre_request(txpPowSupplyAlrmTable_registration * user_context);
    int txpPowSupplyAlrmTable_post_request(txpPowSupplyAlrmTable_registration * user_context,
        int rc);

    int txpPowSupplyAlrmTable_rowreq_ctx_init(txpPowSupplyAlrmTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void txpPowSupplyAlrmTable_rowreq_ctx_cleanup(txpPowSupplyAlrmTable_rowreq_ctx *rowreq_ctx);


    txpPowSupplyAlrmTable_rowreq_ctx *
                  txpPowSupplyAlrmTable_row_find_by_mib_index(txpPowSupplyAlrmTable_mib_index *mib_idx);

extern const oid txpPowSupplyAlrmTable_oid[];
extern const int txpPowSupplyAlrmTable_oid_size;


#include "FTNC-MIB/txpPowSupplyAlrmTable/txpPowSupplyAlrmTable_interface.h"
#include "FTNC-MIB/txpPowSupplyAlrmTable/txpPowSupplyAlrmTable_data_access.h"
#include "FTNC-MIB/txpPowSupplyAlrmTable/txpPowSupplyAlrmTable_data_get.h"
#include "FTNC-MIB/txpPowSupplyAlrmTable/txpPowSupplyAlrmTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* TXPPOWSUPPLYALRMTABLE_H */
/** @} */
