/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef EDFATABLE_DATA_ACCESS_H
#define EDFATABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table edfaTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * FTNC-MIB::edfaTable is subid 8 of mxpConfigMIBObjects.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.43484.1.1.1.2.8, length: 12
*/


    int edfaTable_init_data(edfaTable_registration * edfaTable_reg);


    /*
     * TODO:180:o: Review edfaTable cache timeout.
     * The number of seconds before the cache times out
     */
#define EDFATABLE_CACHE_TIMEOUT   1

void edfaTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void edfaTable_container_shutdown(netsnmp_container *container_ptr);

int edfaTable_container_load(netsnmp_container *container);
void edfaTable_container_free(netsnmp_container *container);

int edfaTable_cache_load(netsnmp_container *container);
void edfaTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int edfaTable_row_prep( edfaTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* EDFATABLE_DATA_ACCESS_H */
