/***********************************************************************/
/* This file contains information proprietary to Cortina Systems, Inc. */
/* (Cortina). Any use or disclosure, in whole or in part, of this      */
/* information to any unauthorized party, for any purposes other than  */
/* that for which it is provided is expressly prohibited except as     */
/* authorized by Cortina in writing. Cortina reserves its rights to    */
/* pursue both civil and criminal penalties for copying or disclosure  */
/* of this material without authorization. Cortina Systems (R),        */
/* Cortina (TM) and the Cortina Systems Earth Logo are the trademarks  */
/* or registered trademarks of Cortina Systems, Inc. and its           */
/* subsidiaries in the U.S. and other countries. Any other product     */
/* and company names are the trademarks of their respective owners.    */
/* Copyright (C) 2006-2013 Cortina Systems, Inc. All rights reserved.  */
/***********************************************************************/
/*
 * ten_n40g_data.h
 *
 * N40G/N10G defines
 *
 * $Id: ten_n40g_data.h,v 1.8 2013/02/22 20:44:38 jccarlis Exp $
 *
 */
 
#ifndef __TEN_NX0G_DATA_H__
#define __TEN_NX0G_DATA_H__

#ifdef __cplusplus
extern "C" {
#endif

#define TEN_NX0G_OTNSM_RAM_UNIT_SIZE 0x20
#define TEN_NX0G_OTNSM_RAM_UNIT_NUM  24

enum ten_kpa_e {
  TEN_KPA_NO_PRBS_FOUND = 0,
  TEN_KPA_PN11 = 1,
  TEN_KPA_PN23 = 2,
  TEN_KPA_PN31 = 3
};

enum ten_kpg_e {
  TEN_KPG_FIXED_PATTERN = 0,
  TEN_KPG_PN11 = 1,
  TEN_KPG_PN23 = 2,
  TEN_KPG_PN31 = 3,
  /* Bugzilla 24360 Start */
  TEN_KPG_DISABLED = 4
  /* Bugzilla 24360 End */
};

enum ten_pattern_e {
  TEN_PATTERN_A,
  TEN_PATTERN_B,
  TEN_PATTERN_MASK
};

enum n40g_otnr4x_e {
  TEN_N40G_OTNR4X_STATUS_SIF,
  TEN_N40G_OTNR4X_STATUS_SOOF,
  TEN_N40G_OTNR4X_STATUS_SLOF,
  TEN_N40G_OTNR4X_STATUS_SPHA,
  TEN_N40G_OTNR4X_STATUS_FST,
  TEN_N40G_OTNR4X_STATUS_PLOST,
  TEN_N40G_OTNR4X_STATUS_PFND,
  TEN_N40G_OTNR4X_STATUS_ALL = 0xFF
};

enum ten_oohr_sm_status_e {
  TEN_NX0G_OOHR_SM_STATUS_APSUNST,
  TEN_NX0G_OOHR_SM_STATUS_DIAE,
  TEN_NX0G_OOHR_SM_STATUS_DBDI,
  TEN_NX0G_OOHR_SM_STATUS_DBIAE,
  TEN_NX0G_OOHR_SM_STATUS_BEISDS,
  TEN_NX0G_OOHR_SM_STATUS_BIPSDS,
  TEN_NX0G_OOHR_SM_STATUS_LOM,
  TEN_NX0G_OOHR_SM_STATUS_ALL = 0xFF
};

enum ten_oohr_tcm_status_e {
  TEN_NX0G_OOHR_TCM_STATUS_ACCSTAT,
  TEN_NX0G_OOHR_TCM_STATUS_STATUNST,
  TEN_NX0G_OOHR_TCM_STATUS_APSUNST,
  TEN_NX0G_OOHR_TCM_STATUS_DLTC,
  TEN_NX0G_OOHR_TCM_STATUS_DAIS,
  TEN_NX0G_OOHR_TCM_STATUS_DOCI,
  TEN_NX0G_OOHR_TCM_STATUS_DLCK,
  TEN_NX0G_OOHR_TCM_STATUS_DIAE,
  TEN_NX0G_OOHR_TCM_STATUS_DBDI,
  TEN_NX0G_OOHR_TCM_STATUS_DBIAE,
  TEN_NX0G_OOHR_TCM_STATUS_BEISDS,
  TEN_NX0G_OOHR_TCM_STATUS_BIPSDS,
  TEN_NX0G_OOHR_TCM_STATUS_ALL = 0xFF
};

enum ten_oohr_pm_e {
  TEN_NX0G_OOHR_PM_STATUS_ACCSTAT,
  TEN_NX0G_OOHR_PM_STATUS_MSIUNST,
  TEN_NX0G_OOHR_PM_STATUS_PTIUNST,
  TEN_NX0G_OOHR_PM_STATUS_STATUNST,
  TEN_NX0G_OOHR_PM_STATUS_APSUNST,
  TEN_NX0G_OOHR_PM_STATUS_DCBRAIS,
  TEN_NX0G_OOHR_PM_STATUS_DMSIM,
  TEN_NX0G_OOHR_PM_STATUS_DPLM,
  TEN_NX0G_OOHR_PM_STATUS_DAIS,
  TEN_NX0G_OOHR_PM_STATUS_DOCI,
  TEN_NX0G_OOHR_PM_STATUS_DLCK,
  TEN_NX0G_OOHR_PM_STATUS_DBDI,
  TEN_NX0G_OOHR_PM_STATUS_BEISDS,
  TEN_NX0G_OOHR_PM_STATUS_BIPSDS,
  TEN_NX0G_OOHR_PM_STATUS_ALL = 0xFF
};

enum ten_oohr_status_sedtm_e {
  TEN_NX0G_OOHR_STATUS_SE1DTM  = 1,
  TEN_NX0G_OOHR_STATUS_SE2DTM  = 2,
  TEN_NX0G_OOHR_STATUS_SE3DTM  = 3,  
  TEN_NX0G_OOHR_STATUS_SE4DTM  = 4,
  TEN_NX0G_OOHR_STATUS_SE5DTM  = 5,
  TEN_NX0G_OOHR_STATUS_SE6DTM  = 6,
  TEN_NX0G_OOHR_STATUS_SE7DTM  = 7,
  TEN_NX0G_OOHR_STATUS_SE8DTM  = 8,
  TEN_NX0G_OOHR_STATUS_SE9DTM  = 9,
  TEN_NX0G_OOHR_STATUS_SE10DTM = 10,
  TEN_NX0G_OOHR_STATUS_SE11DTM = 11,
  TEN_NX0G_OOHR_STATUS_SE12DTM = 12,
  TEN_NX0G_OOHR_STATUS_SE13DTM = 13,
  TEN_NX0G_OOHR_STATUS_SE14DTM = 14,
  TEN_NX0G_OOHR_STATUS_SE15DTM = 15,
  TEN_NX0G_OOHR_STATUS_SE16DTM = 16,
  TEN_NX0G_OOHR_STATUS_SE17DTM = 17, 
  TEN_NX0G_OOHR_STATUS_SE18DTM = 18,
  TEN_NX0G_OOHR_STATUS_SE19DTM = 19,
  TEN_NX0G_OOHR_STATUS_SE20DTM = 20,
  TEN_NX0G_OOHR_STATUS_SE21DTM = 21,
  TEN_NX0G_OOHR_STATUS_SE22DTM = 22,
  TEN_NX0G_OOHR_STATUS_SE23DTM = 23,
  TEN_NX0G_OOHR_STATUS_SE24DTM = 24,
  TEN_NX0G_OOHR_STATUS_SEDTM_ALL = 0xFF
};
 
enum ten_oohr_status_sest_e {
  TEN_NX0G_OOHR_STATUS_SE1ST = 1,
  TEN_NX0G_OOHR_STATUS_SE2ST,
  TEN_NX0G_OOHR_STATUS_SE3ST,
  TEN_NX0G_OOHR_STATUS_SE4ST,
  TEN_NX0G_OOHR_STATUS_SE5ST,
  TEN_NX0G_OOHR_STATUS_SE6ST,
  TEN_NX0G_OOHR_STATUS_SE7ST,
  TEN_NX0G_OOHR_STATUS_SE8ST,
  TEN_NX0G_OOHR_STATUS_SE9ST,
  TEN_NX0G_OOHR_STATUS_SE10ST,
  TEN_NX0G_OOHR_STATUS_SE11ST,
  TEN_NX0G_OOHR_STATUS_SE12ST,
  TEN_NX0G_OOHR_STATUS_SE13ST,
  TEN_NX0G_OOHR_STATUS_SE14ST,
  TEN_NX0G_OOHR_STATUS_SE15ST,
  TEN_NX0G_OOHR_STATUS_SE16ST,
  TEN_NX0G_OOHR_STATUS_SE17ST,
  TEN_NX0G_OOHR_STATUS_SE18ST,
  TEN_NX0G_OOHR_STATUS_SE19ST,
  TEN_NX0G_OOHR_STATUS_SE20ST,
  TEN_NX0G_OOHR_STATUS_SE21ST,
  TEN_NX0G_OOHR_STATUS_SE22ST,
  TEN_NX0G_OOHR_STATUS_SE23ST,
  TEN_NX0G_OOHR_STATUS_SE24ST,
  TEN_NX0G_OOHR_STATUS_ALL = 0xFF
};

enum ten_oohr_gaf_e {
  TEN_NX0G_OOHR_GAF_STATUS_AFE,
  TEN_NX0G_OOHR_GAF_STATUS_AFU,
  TEN_NX0G_OOHR_GAF_STATUS_AFVAL,
  TEN_NX0G_OOHR_GAF_STATUS_ALL = 0xFF
};

enum ten_oohr_ovrhd_e {
  TEN_OVRHD_FILTERED_K1,
  TEN_OVRHD_FILTERED_K2,
  TEN_OVRHD_EXTRACTED_S1
};

enum ten_sdfr_sdfstat_e {
  TEN_SDFR_SDFSTAT_PN11S,
  TEN_SDFR_SDFSTAT_SD,
  TEN_SDFR_SDFSTAT_SF,
  TEN_SDFR_SDFSTAT_B1INVS,
  TEN_SDFR_SDFSTAT_LOSS,
  TEN_SDFR_SDFSTAT_LOFS,
  TEN_SDFR_SDFSTAT_OOFS,
  TEN_SDFR_SDFSTAT_ALL = 0xFF
};

enum ten_set_poh_e {
  TEN_SET_POH_C2 = 0,
  TEN_SET_POH_F2 = 1,
  TEN_SET_POH_G1 = 2,
  TEN_SET_POH_F3 = 3,
  TEN_SET_POH_H4 = 4,
  TEN_SET_POH_N1 = 5,
  TEN_SET_POH_K3 = 6,
  TEN_SET_POH_PFIXSF = 7,
  TEN_SET_POH_B3MSK = 8
};

enum ten_get_poh_e {
  TEN_GET_POH_C2,
  TEN_GET_POH_F2,
  TEN_GET_POH_G1,
  TEN_GET_POH_F3,
  TEN_GET_POH_H4,
  TEN_GET_POH_N1,
  TEN_GET_POH_K3
};

enum ten_soh_e {
  TEN_SOH_M0,
  TEN_SOH_M1,
  TEN_SOH_DCM,
  TEN_SOH_DCR,
  TEN_SOH_K2,
  TEN_SOH_K1,
  TEN_SOH_OHDEF,
  TEN_SOH_NU9,
  TEN_SOH_NU2,
  TEN_SOH_NU1,
  TEN_SOH_SSBITS,
  TEN_SOH_E1,
  TEN_SOH_F1,
  TEN_SOH_S1,
  TEN_SOH_E2
};

enum ten_poh_e {
  TEN_POH_J1      = 0,
  TEN_POH_SSBITS  = 1,
  TEN_POH_G1      = 2,
  TEN_POH_C2      = 3,
  TEN_POH_H4      = 4,
  TEN_POH_F2      = 5,
  TEN_POH_K3      = 6,
  TEN_POH_F3      = 7,
  TEN_POH_PFIXSTF = 8,
  TEN_POH_N1      = 9
};

enum ten_nx0g_otnr_e {
  TEN_NX0G_OTNR_OFSTAT_FSUSTS,
  TEN_NX0G_OTNR_OFSTAT_SIF,
  TEN_NX0G_OTNR_OFSTAT_SOOF,
  TEN_NX0G_OTNR_OFSTAT_SLOF,
  TEN_NX0G_OTNR_OFSTAT_SPHA,
  TEN_NX0G_OTNR_OFSTAT_FST,
  TEN_NX0G_OTNR_OFSTAT_PN11S,
  TEN_NX0G_OTNR_OFSTAT_ALL = 0xFF
};

enum ten_nx0g_pohr_e {
  TEN_NX0G_POHR_OHPSTAT0_G1USTS,
  TEN_NX0G_POHR_OHPSTAT0_RDIPS,
  TEN_NX0G_POHR_OHPSTAT0_VCAIS,
  TEN_NX0G_POHR_OHPSTAT0_UNEQPS,
  TEN_NX0G_POHR_OHPSTAT0_PLMS,
  TEN_NX0G_POHR_OHPSTAT0_C2USTS,
  TEN_NX0G_POHR_OHPSTAT0_SD,
  TEN_NX0G_POHR_OHPSTAT0_SF,
  TEN_NX0G_POHR_OHPSTAT0_J1CRC,
  TEN_NX0G_POHR_OHPSTAT0_J1ALLZERO,
  TEN_NX0G_POHR_OHPSTAT0_PTIM,
  TEN_NX0G_POHR_OHPSTAT0_J1USTS,
  TEN_NX0G_POHR_OHPSTAT0_ALL = 0xFF
};

enum ten_nx0g_sohr_e {
  TEN_NX0G_SOHR_OHPSTAT_AISC,
  TEN_NX0G_SOHR_OHPSTAT_AIS,
  TEN_NX0G_SOHR_OHPSTAT_LOPC,
  TEN_NX0G_SOHR_OHPSTAT_LOP,
  TEN_NX0G_SOHR_OHPSTAT_S1USTS,
  TEN_NX0G_SOHR_OHPSTAT_K12USTS,
  TEN_NX0G_SOHR_OHPSTAT_LRDI,
  TEN_NX0G_SOHR_OHPSTAT_LAIS,
  TEN_NX0G_SOHR_OHPSTAT_DCCMUSTS,
  TEN_NX0G_SOHR_OHPSTAT_DCCRUSTS,
  TEN_NX0G_SOHR_OHPSTAT_J0CRC,
  TEN_NX0G_SOHR_OHPSTAT_RSTIM,
  TEN_NX0G_SOHR_OHPSTAT_J0USTS,
  TEN_NX0G_SOHR_OHPSTAT_ALL = 0xFF
};

enum ten_n40g_set_global_resets_enums {
  TEN_N40G_GLOBAL_RESETS_RSTTX  = 0x0001,
  TEN_N40G_GLOBAL_RESETS_RSTOT  = 0x0002,
  TEN_N40G_GLOBAL_RESETS_RSTST  = 0x0004,
  TEN_N40G_GLOBAL_RESETS_RSTRX  = 0x0010,
  TEN_N40G_GLOBAL_RESETS_RSTOR  = 0x0020,
  TEN_N40G_GLOBAL_RESETS_RSTSR  = 0x0040,
  TEN_N40G_GLOBAL_RESETS_RSTSYS = 0x0100,
  TEN_N40G_GLOBAL_RESETS_ALL    = 0x0177
};

enum n40g_st4x_ohie_enums {
  TEN_N40G_ST4X_OHIE_A1A2IE     =  0,
  TEN_N40G_ST4X_OHIE_A1A2RSH    =  1,
  TEN_N40G_ST4X_OHIE_A1A2INV    =  2,
  TEN_N40G_ST4X_OHIE_ErrFawEna  =  3,
  TEN_N40G_ST4X_OHIE_PRBSIE     =  4,
  TEN_N40G_ST4X_OHIE_POHIE      =  5,
  TEN_N40G_ST4X_OHIE_SCREN      =  6,
  TEN_N40G_ST4X_OHIE_B1IE       =  7,
  TEN_N40G_ST4X_OHIE_B1TRANS    =  8,
  TEN_N40G_ST4X_OHIE_B1INV      =  9
};

/* Bugzilla 29751 Start */
enum n40g_gbl4x_gblint_enums {
  TEN_N40G_GBL4X_GBLINT_SMECCSGL        = 0x0001,
  TEN_N40G_GBL4X_GBLINT_SMECCDBL        = 0x0002,		
  TEN_N40G_GBL4X_GBLINT_TXDSKERR        = 0x0004,
  TEN_NX0G_GBL4X_GBLINT_ALL				= 0x0007
};

enum n40g_otnr4x_intr_enums {
  TEN_N40G_OTNR4X_INTR_IPSFND	= 0x0001,
  TEN_N40G_OTNR4X_INTR_IPLOST	= 0x0002,
  TEN_N40G_OTNR4X_INTR_IOOF		= 0x0004,
  TEN_N40G_OTNR4X_INTR_ILOF		= 0x0008,
  TEN_N40G_OTNR4X_INTR_IIF		= 0x0010,
  TEN_N40G_OTNR4X_INTR_FSCH		= 0x0020,
  TEN_N40G_OTNR4X_INTR_FSUSTSI	= 0x0040,
  TEN_N40G_OTNR4X_INTR_GMP0I	= 0x0080,
  TEN_N40G_OTNR4X_INTR_GMP1I	= 0x0100,
  TEN_N40G_OTNR4X_INTR_GMP2I	= 0x0200,
  TEN_N40G_OTNR4X_INTR_GMP3I	= 0x0400,
  TEN_N40G_OTNR4X_INTR_FSMMI	= 0x0800,
  TEN_N40G_OTNR4X_INTR_OBFA2I	= 0x1000,
  TEN_N40G_OTNR4X_INTR_FAWMI	= 0x2000,
  TEN_N40G_OTNR4X_INTR_FSMMTRBI	= 0x4000,
  TEN_N40G_OTNR4X_INTR_ALL		= 0x3FFF
};

enum n40g_sdfr_sdfist_enums {
  TEN_N40G_SDFR_SDFIST_OOF	  =	0x0001,
  TEN_N40G_SDFR_SDFIST_LOF	  =	0x0002,
  TEN_N40G_SDFR_SDFIST_LOS	  =	0x0004,
  TEN_N40G_SDFR_SDFIST_FER	  =	0x0008,
  TEN_N40G_SDFR_SDFIST_FOK	  =	0x0010,

  TEN_N40G_SDFR_SDFIST_B1INVI =	0x0040,
  TEN_N40G_SDFR_SDFIST_B1BTEX =	0x0080,
  TEN_N40G_SDFR_SDFIST_B1BLEX =	0x0100,
  TEN_N40G_SDFR_SDFIST_B2BTEX =	0x0200,
  TEN_N40G_SDFR_SDFIST_B2BLEX = 0x0400, 
  TEN_N40G_SDFR_SDFIST_SFI	  =	0x0800,
  TEN_N40G_SDFR_SDFIST_SDI	  =	0x1000,

  TEN_N40G_SDFR_SDFIST_IPN11  =	0x8000,
  TEN_N40G_SDFR_SDFIST_ALL	  = 0x9FDF
};
/* Bugzilla 29751 End */

enum ten_n40g_oohr_acmsi_enums {
  TEN_N40G_OOHR_ACCEPTED_MSI_EXT7 = 15,
  TEN_N40G_OOHR_ACCEPTED_MSI_EXT6 = 14,
  TEN_N40G_OOHR_ACCEPTED_MSI_EXT5 = 13, 
  TEN_N40G_OOHR_ACCEPTED_MSI_EXT4 = 12,
  TEN_N40G_OOHR_ACCEPTED_MSI_EXT3 = 11, 
  TEN_N40G_OOHR_ACCEPTED_MSI_EXT2 = 10,
  TEN_N40G_OOHR_ACCEPTED_MSI_EXT1 = 9,
  TEN_N40G_OOHR_ACCEPTED_MSI_EXT0 = 8,
  TEN_N40G_OOHR_ACCEPTED_MSI7 = 7,
  TEN_N40G_OOHR_ACCEPTED_MSI6 = 6,
  TEN_N40G_OOHR_ACCEPTED_MSI5 = 5,
  TEN_N40G_OOHR_ACCEPTED_MSI4 = 4,
  TEN_N40G_OOHR_ACCEPTED_MSI3 = 3,
  TEN_N40G_OOHR_ACCEPTED_MSI2 = 2,
  TEN_N40G_OOHR_ACCEPTED_MSI1 = 1,
  TEN_N40G_OOHR_ACCEPTED_MSI0 = 0
};

#ifdef __cplusplus
}
#endif
#endif
