/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "tpClient4SeverityTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement tpClient4SeverityTable get routines.
 * TODO:240:M: Implement tpClient4SeverityTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table tpClient4SeverityTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * FTNC-MIB::tpClient4SeverityTable is subid 5 of tpAlarms.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5, length: 12
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement tpClient4SeverityTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param tpClient4SeverityIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
tpClient4SeverityTable_indexes_set_tbl_idx(tpClient4SeverityTable_mib_index *tbl_idx, long tpClient4SeverityIndex_val)
{
    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityTable_indexes_set_tbl_idx","called\n"));

    /* tpClient4SeverityIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/R/d/h */
    tbl_idx->tpClient4SeverityIndex = tpClient4SeverityIndex_val;
    

    return MFD_SUCCESS;
} /* tpClient4SeverityTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
tpClient4SeverityTable_indexes_set(tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long tpClient4SeverityIndex_val)
{
    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityTable_indexes_set","called\n"));

    if(MFD_SUCCESS != tpClient4SeverityTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , tpClient4SeverityIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != tpClient4SeverityTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* tpClient4SeverityTable_indexes_set */


/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityFramerFsmms
 * tpClient4SeverityFramerFsmms is subid 2 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.2
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityFramerFsmms data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityFramerFsmms_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityFramerFsmms_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityFramerFsmms_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityFramerFsmms_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityFramerFsmms_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityFramerFsmms data.
 * copy (* tpClient4SeverityFramerFsmms_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityFramerFsmms_val_ptr ) = rowreq_ctx->data.tpClient4SeverityFramerFsmms;

    return MFD_SUCCESS;
} /* tpClient4SeverityFramerFsmms_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityFramerFssusts
 * tpClient4SeverityFramerFssusts is subid 3 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.3
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityFramerFssusts data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityFramerFssusts_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityFramerFssusts_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityFramerFssusts_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityFramerFssusts_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityFramerFssusts_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityFramerFssusts data.
 * copy (* tpClient4SeverityFramerFssusts_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityFramerFssusts_val_ptr ) = rowreq_ctx->data.tpClient4SeverityFramerFssusts;

    return MFD_SUCCESS;
} /* tpClient4SeverityFramerFssusts_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityFramerSoof
 * tpClient4SeverityFramerSoof is subid 4 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.4
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityFramerSoof data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityFramerSoof_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityFramerSoof_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityFramerSoof_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityFramerSoof_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityFramerSoof_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityFramerSoof data.
 * copy (* tpClient4SeverityFramerSoof_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityFramerSoof_val_ptr ) = rowreq_ctx->data.tpClient4SeverityFramerSoof;

    return MFD_SUCCESS;
} /* tpClient4SeverityFramerSoof_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityFramerSlof
 * tpClient4SeverityFramerSlof is subid 5 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.5
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityFramerSlof data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityFramerSlof_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityFramerSlof_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityFramerSlof_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityFramerSlof_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityFramerSlof_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityFramerSlof data.
 * copy (* tpClient4SeverityFramerSlof_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityFramerSlof_val_ptr ) = rowreq_ctx->data.tpClient4SeverityFramerSlof;

    return MFD_SUCCESS;
} /* tpClient4SeverityFramerSlof_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityFramerSif
 * tpClient4SeverityFramerSif is subid 6 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.6
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityFramerSif data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityFramerSif_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityFramerSif_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityFramerSif_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityFramerSif_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityFramerSif_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityFramerSif data.
 * copy (* tpClient4SeverityFramerSif_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityFramerSif_val_ptr ) = rowreq_ctx->data.tpClient4SeverityFramerSif;

    return MFD_SUCCESS;
} /* tpClient4SeverityFramerSif_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityFramerFst
 * tpClient4SeverityFramerFst is subid 7 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.7
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityFramerFst data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityFramerFst_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityFramerFst_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityFramerFst_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityFramerFst_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityFramerFst_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityFramerFst data.
 * copy (* tpClient4SeverityFramerFst_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityFramerFst_val_ptr ) = rowreq_ctx->data.tpClient4SeverityFramerFst;

    return MFD_SUCCESS;
} /* tpClient4SeverityFramerFst_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityLosstatLosf
 * tpClient4SeverityLosstatLosf is subid 8 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.8
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityLosstatLosf data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityLosstatLosf_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityLosstatLosf_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityLosstatLosf_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityLosstatLosf_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityLosstatLosf_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityLosstatLosf data.
 * copy (* tpClient4SeverityLosstatLosf_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityLosstatLosf_val_ptr ) = rowreq_ctx->data.tpClient4SeverityLosstatLosf;

    return MFD_SUCCESS;
} /* tpClient4SeverityLosstatLosf_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityPathmonAccstat
 * tpClient4SeverityPathmonAccstat is subid 9 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.9
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityPathmonAccstat data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityPathmonAccstat_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityPathmonAccstat_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityPathmonAccstat_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityPathmonAccstat_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityPathmonAccstat_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityPathmonAccstat data.
 * copy (* tpClient4SeverityPathmonAccstat_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityPathmonAccstat_val_ptr ) = rowreq_ctx->data.tpClient4SeverityPathmonAccstat;

    return MFD_SUCCESS;
} /* tpClient4SeverityPathmonAccstat_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityPathmonDais
 * tpClient4SeverityPathmonDais is subid 10 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.10
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityPathmonDais data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityPathmonDais_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityPathmonDais_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityPathmonDais_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityPathmonDais_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityPathmonDais_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityPathmonDais data.
 * copy (* tpClient4SeverityPathmonDais_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityPathmonDais_val_ptr ) = rowreq_ctx->data.tpClient4SeverityPathmonDais;

    return MFD_SUCCESS;
} /* tpClient4SeverityPathmonDais_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityPathmonDbdi
 * tpClient4SeverityPathmonDbdi is subid 11 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.11
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityPathmonDbdi data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityPathmonDbdi_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityPathmonDbdi_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityPathmonDbdi_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityPathmonDbdi_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityPathmonDbdi_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityPathmonDbdi data.
 * copy (* tpClient4SeverityPathmonDbdi_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityPathmonDbdi_val_ptr ) = rowreq_ctx->data.tpClient4SeverityPathmonDbdi;

    return MFD_SUCCESS;
} /* tpClient4SeverityPathmonDbdi_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityPathmonDlck
 * tpClient4SeverityPathmonDlck is subid 12 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.12
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityPathmonDlck data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityPathmonDlck_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityPathmonDlck_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityPathmonDlck_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityPathmonDlck_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityPathmonDlck_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityPathmonDlck data.
 * copy (* tpClient4SeverityPathmonDlck_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityPathmonDlck_val_ptr ) = rowreq_ctx->data.tpClient4SeverityPathmonDlck;

    return MFD_SUCCESS;
} /* tpClient4SeverityPathmonDlck_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeverityPathmonMsiunst
 * tpClient4SeverityPathmonMsiunst is subid 13 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.13
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeverityPathmonMsiunst data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeverityPathmonMsiunst_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeverityPathmonMsiunst_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeverityPathmonMsiunst_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeverityPathmonMsiunst_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeverityPathmonMsiunst_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeverityPathmonMsiunst data.
 * copy (* tpClient4SeverityPathmonMsiunst_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeverityPathmonMsiunst_val_ptr ) = rowreq_ctx->data.tpClient4SeverityPathmonMsiunst;

    return MFD_SUCCESS;
} /* tpClient4SeverityPathmonMsiunst_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeveritySecmonBipsfs
 * tpClient4SeveritySecmonBipsfs is subid 14 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.14
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeveritySecmonBipsfs data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeveritySecmonBipsfs_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeveritySecmonBipsfs_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeveritySecmonBipsfs_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeveritySecmonBipsfs_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeveritySecmonBipsfs_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeveritySecmonBipsfs data.
 * copy (* tpClient4SeveritySecmonBipsfs_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeveritySecmonBipsfs_val_ptr ) = rowreq_ctx->data.tpClient4SeveritySecmonBipsfs;

    return MFD_SUCCESS;
} /* tpClient4SeveritySecmonBipsfs_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeveritySecmonDbdi
 * tpClient4SeveritySecmonDbdi is subid 15 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.15
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeveritySecmonDbdi data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeveritySecmonDbdi_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeveritySecmonDbdi_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeveritySecmonDbdi_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeveritySecmonDbdi_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeveritySecmonDbdi_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeveritySecmonDbdi data.
 * copy (* tpClient4SeveritySecmonDbdi_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeveritySecmonDbdi_val_ptr ) = rowreq_ctx->data.tpClient4SeveritySecmonDbdi;

    return MFD_SUCCESS;
} /* tpClient4SeveritySecmonDbdi_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeveritySecmonDiae
 * tpClient4SeveritySecmonDiae is subid 16 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.16
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeveritySecmonDiae data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeveritySecmonDiae_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeveritySecmonDiae_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeveritySecmonDiae_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeveritySecmonDiae_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeveritySecmonDiae_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeveritySecmonDiae data.
 * copy (* tpClient4SeveritySecmonDiae_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeveritySecmonDiae_val_ptr ) = rowreq_ctx->data.tpClient4SeveritySecmonDiae;

    return MFD_SUCCESS;
} /* tpClient4SeveritySecmonDiae_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeveritySecmonFlom
 * tpClient4SeveritySecmonFlom is subid 17 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.17
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeveritySecmonFlom data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeveritySecmonFlom_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeveritySecmonFlom_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeveritySecmonFlom_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeveritySecmonFlom_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeveritySecmonFlom_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeveritySecmonFlom data.
 * copy (* tpClient4SeveritySecmonFlom_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeveritySecmonFlom_val_ptr ) = rowreq_ctx->data.tpClient4SeveritySecmonFlom;

    return MFD_SUCCESS;
} /* tpClient4SeveritySecmonFlom_get */

/*---------------------------------------------------------------------
 * FTNC-MIB::tpClient4SeverityEntry.tpClient4SeveritySecmonLom
 * tpClient4SeveritySecmonLom is subid 18 of tpClient4SeverityEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.43484.1.1.3.6.5.1.18
 * Description:
alarm severity
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the tpClient4SeveritySecmonLom data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param tpClient4SeveritySecmonLom_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
tpClient4SeveritySecmonLom_get( tpClient4SeverityTable_rowreq_ctx *rowreq_ctx, long * tpClient4SeveritySecmonLom_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != tpClient4SeveritySecmonLom_val_ptr );


    DEBUGMSGTL(("verbose:tpClient4SeverityTable:tpClient4SeveritySecmonLom_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the tpClient4SeveritySecmonLom data.
 * copy (* tpClient4SeveritySecmonLom_val_ptr ) from rowreq_ctx->data
 */
    (* tpClient4SeveritySecmonLom_val_ptr ) = rowreq_ctx->data.tpClient4SeveritySecmonLom;

    return MFD_SUCCESS;
} /* tpClient4SeveritySecmonLom_get */



/** @} */
