/***********************************************************************/
/* This file contains information proprietary to Cortina Systems, Inc. */
/* (Cortina). Any use or disclosure, in whole or in part, of this      */
/* information to any unauthorized party, for any purposes other than  */
/* that for which it is provided is expressly prohibited except as     */
/* authorized by Cortina in writing. Cortina reserves its rights to    */
/* pursue both civil and criminal penalties for copying or disclosure  */
/* of this material without authorization. Cortina Systems (R),        */
/* Cortina (TM) and the Cortina Systems Earth Logo are the trademarks  */
/* or registered trademarks of Cortina Systems, Inc. and its           */
/* subsidiaries in the U.S. and other countries. Any other product     */
/* and company names are the trademarks of their respective owners.    */
/* Copyright (C) 2006-2010 by Cortina Systems, Inc. All rights reserved. */
/***********************************************************************/

/*
 * This file is auto-generated; DO NOT MODIFY
 */

#ifndef __TEN_IRQ_TREE_H__
#define __TEN_IRQ_TREE_H__

#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */

#include "tenabo40.h"

#define TEN_IRQ_NODE_NO_NODE        0
#define TEN_IRQ_NODE_SLICED_NO_NODE 0
#define TEN_IRQ_NO_HANDLER          0
#define TEN_IRQ_NO_STATUS           0

extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_GLOBAL_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_MODULE_A_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_PROTOCOL_Interrupt;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_Int;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_RXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_RXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_RXVCO1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_RXVCO2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_RXVCO3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_RXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_RXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_RXLOCKD1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_RXLOCKD2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_RXLOCKD3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_RXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_TXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_TXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_TXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_TXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_TXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_PRBSCHKi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_PRBSCHK0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_PRBSCHK1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_PRBSCHK2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC0_MR10X4_SDS_COMMON_PRBSCHK3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_Int;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXVCO1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXVCO2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXVCO3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXVCO4_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXLOCKD1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXLOCKD2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXLOCKD3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXLOCKD4_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_RXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_TXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_TXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_TXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_TXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_TXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_PRBSCHKi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_PRBSCHK0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_PRBSCHK1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_PRBSCHK2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_PRBSCHK3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC1_MR10X5_SDS_COMMON_PRBSCHK4_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_Int;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_RXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_RXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_RXVCO1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_RXVCO2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_RXVCO3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_RXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_RXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_RXLOCKD1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_RXLOCKD2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_RXLOCKD3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_RXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_TXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_TXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_TXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_TXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_TXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_PRBSCHKi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_PRBSCHK0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_PRBSCHK1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_PRBSCHK2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC2_MR10X4_SDS_COMMON_PRBSCHK3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_Int;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXVCO1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXVCO2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXVCO3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXVCO4_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXLOCKD1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXLOCKD2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXLOCKD3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXLOCKD4_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_RXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_TXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_TXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_TXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_TXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_TXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_PRBSCHKi;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_PRBSCHK0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_PRBSCHK1_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_PRBSCHK2_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_PRBSCHK3_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_MR_SLC3_MR10X5_SDS_COMMON_PRBSCHK4_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_TOP_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INT_SUM0;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT0;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT1;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT2;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT3;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT4;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT5;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT6;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT7;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT8;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT9;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT10;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT11;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT12;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT13;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT14;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT15;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INT_SUM1;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI5_SLICE_INTERRUPT16;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI42_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI42_STD_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_SFI42_EDS_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_PROTOCOL_LBELST_INT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_PROTOCOL_PSELST_INT;
extern ten_irq_node_t          TEN_IRQ_NODE_HSIF_PROTOCOL_PSWITCH_MUX_INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_GBL4X_INTH;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_GBLR4X_INTR0;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OTNR4X_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OTNR4X_FSCHI;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OTNR4X_FSUSTI;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OGMPR4X_GMPINT0;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OGMPR4X_GMPINT1;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OGMPR4X_GMPINT2;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OGMPR4X_GMPINT3;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OTNR4X_FSMMI;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OTNR4X_OBFA2_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OTNR4X_FSMMTRBI;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_SDFR_SDFIST;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_INTH;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_SMINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_PMINT0;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_PMINT1;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_TCM1INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_TCM2INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_TCM3INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_TCM4INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_TCM5INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_TCM6INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_MFMINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_SEINTH;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_SEINT0;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_SEINT1;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_SEINT2;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_AFINTH;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_AFINT0;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_AFINT1;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_AFINT2;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_AFINT3;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_AFINT4;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_DMCSFINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OOHR_AGGINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OTNT4X_INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_OTNT4X_GMPINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_GBL4X_GBLINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_MLDRX_MLDR_MLDINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_MLDRX_SADECO_SADINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_MLDRX_MLDR_LANEINT0;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_MLDRX_MLDR_LANEINT1;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_MLDRX_MLDR_LANEINT2;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_MLDRX_MLDR_LANEINT3;
extern ten_irq_node_t          TEN_IRQ_NODE_N40G_MLDRX_MLD_ES_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_OHPP_SFU_INTRHIER;
extern ten_irq_node_t          TEN_IRQ_NODE_OHPP_SFU_INTR0;
extern ten_irq_node_t          TEN_IRQ_NODE_OHPP_SFU_INTR1;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_GBL_INTH;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_GBLR_INTH;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_GBLR_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OTNR_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OGMPR_GMPINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SDFR_SDFIST;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_INTH;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_SMINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_PMINT0;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_PMINT1;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_TCM1INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_TCM2INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_TCM3INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_TCM4INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_TCM5INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_TCM6INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_MFMINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_SEINTH;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_SEINT0;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_SEINT1;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_SEINT2;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_AFINTH;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_AFINT0;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_AFINT1;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_AFINT2;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_AFINT3;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_AFINT4;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_DMCSFINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OOHR_AGGINT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_INTH;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_INTH0;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII0;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII1;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII2;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII3;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII4;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII5;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII6;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII7;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII8;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII9;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII10;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII11;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_PII12;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_INTH1;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_OHCH;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_OHRCVDSTI;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_OHSTI;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_OHINST0;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_OHINST1;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHR_ECCINTR;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_POHR_INTH;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_POHR_OHINST0;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_POHR_OHINST1;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_OTNT_INT;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_SOHT_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_N10G_GBL_GBLINT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_MISC_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_MISC_INTERRUPT_RX;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_PCS_RX_RXINT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_RS_RX_RXINT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_BASEX_XAUI_RX_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_GFP_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_XCODE_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_FC_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_FC_RX_R_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_FC_RX_M_INTERRUPT0;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_FC_RX_M_INTERRUPT1;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_EGPCS_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_XGADJ_RX_INT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_MON10B_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_BER10B_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_MAC_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_MISC_INTERRUPT_TX;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_PCS_TX_TXINT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_RS_TX_TXINT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_BASEX_XAUI_TX_TX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_GFP_TX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_XCODE_TX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_MAC_TX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_EGPCS_TX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_XGADJ_TX_INT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP10G_PM_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP40G_MISC_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP40G_MISC_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP40G_LIF_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP40G_PCS_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP40G_PCS_RX_LDBINTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP40G_RS_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP40G_MISC_TX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP40G_PCS_TX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP40G_PBERT40G_TX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_PP40G_PM_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_MODULE_B_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_XFI_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_Int;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_RXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_RXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_RXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_RXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_RXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_TXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_TXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_TXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_TXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_TXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_PRBSCHKi;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI32X1_SDS_XFI32X1_SDS_COMMON_PRBSCHK0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_XFI_ECC_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_CFP_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_Int;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_RXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_RXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_RXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_RXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_RXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_TXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_TXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_TXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_TXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_TXELSTi;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_PRBSCHKi;
extern ten_irq_node_t          TEN_IRQ_NODE_CFP32X1_SDS_COMMON_PRBSCHK0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_CUPLL_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_XFI_CUPLL_LOCKDET_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_GFEC_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_GFEC40G_FRX40_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_GFEC40G_FTX40_INTT;
extern ten_irq_node_t          TEN_IRQ_NODE_GFEC10G_FRX_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_GFEC10G_FTX_INTT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_UFEC_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_URX_URXINT;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_URX_ECC_URX_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_URX_ECC_EDRX_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_URX_ECC_RX9_I1_PART1_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_URX_ECC_RX9_I1_PART2_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_URX_ECC_RX9_I2_PART1_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_URX_ECC_RX9_I2_PART2_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_URX_ECC_RX10_I1_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_URX_ECC_RX10_I2_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_URX_ECC_RX10_I3_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_URX_ECC_UHMRX_INTR;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_UTX_UTXINT;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_UTX_ECC_UTX_INTT;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_UTX_ECC_EDTX_INTT;
extern ten_irq_node_t          TEN_IRQ_NODE_UFEC_UTX_ECC_UHMTX_INTT;
extern ten_irq_node_t          TEN_IRQ_NODE_XCON_GLB_TOP_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_XCON_GLB_CBERT_INT_SUMMARY;
extern ten_irq_node_t          TEN_IRQ_NODE_XCON_CBERT_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_XCON_GLB_ES_INT_SUMMARY;
extern ten_irq_node_t          TEN_IRQ_NODE_XCON_ES_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_XCON_SADECO_SADINT;
extern ten_irq_node_t          TEN_IRQ_NODE_XCON_GLB_PBERT_RX_INT_SUMMARY;
extern ten_irq_node_t          TEN_IRQ_NODE_XCON_PBERT_RX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_XCON_GLB_PBERT_TX_INT_SUMMARY;
extern ten_irq_node_t          TEN_IRQ_NODE_XCON_PBERT_TX_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_SPOH_SerIntfInt;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_GS_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_GPLL_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_GPLLX1_SDS_COMMON_Int;
extern ten_irq_node_t          TEN_IRQ_NODE_GPLLX1_SDS_COMMON_TXVCOi;
extern ten_irq_node_t          TEN_IRQ_NODE_GPLLX1_SDS_COMMON_TXVCO0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_GPLLX1_SDS_COMMON_TXLOCKDi;
extern ten_irq_node_t          TEN_IRQ_NODE_GPLLX1_SDS_COMMON_TXLOCKD0_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_SYNCDSYNC_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_SYNCDSYNCRX_CFGMONRX_INT;
extern ten_irq_node_t          TEN_IRQ_NODE_SYNCDSYNCTX_CFGMONTX_INT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_CLOCK_LOSS_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_XLOS_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_SYS_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_SYS_CLK_FAIL_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_MPIF_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_GPIO_F_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_GPIO_R_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_MISC_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_CLOCK_SWITCH_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_CLOCK_SWITCH_REV_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_DATA_SWITCH_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_CUPLL_HOLDOVER_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_MPIF_MR_PROT_INTERRUPT;
extern ten_irq_node_t          TEN_IRQ_NODE_DM_INTR;

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif
