/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file txpSeverityTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef TXPSEVERITYTABLE_DATA_GET_H
#define TXPSEVERITYTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table txpSeverityTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * FTNC-MIB::txpSeverityTable is subid 1 of txpAlarms.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.43484.1.1.3.4.1, length: 12
*/
    /*
     * indexes
     */

int txpSeverityEol_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityEol_val_ptr );
int txpSeverityModTemp_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityModTemp_val_ptr );
int txpSeverityTxooa_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityTxooa_val_ptr );
int txpSeverityTxLof_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityTxLof_val_ptr );
int txpSeverityTxDsc_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityTxDsc_val_ptr );
int txpSeverityLsWav_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityLsWav_val_ptr );
int txpSeverityLsBias_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityLsBias_val_ptr );
int txpSeverityLsTemp_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityLsTemp_val_ptr );
int txpSeverityTxLock_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityTxLock_val_ptr );
int txpSeverityLsPow_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityLsPow_val_ptr );
int txpSeverityModBias_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityModBias_val_ptr );
int txpSeverityLatchedTxFifo_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityLatchedTxFifo_val_ptr );
int txpSeverityRxPow_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityRxPow_val_ptr );
int txpSeverityRxLos_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityRxLos_val_ptr );
int txpSeverityRxLock_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityRxLock_val_ptr );
int txpSeverityRxs_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityRxs_val_ptr );
int txpSeverityPrbsErr_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityPrbsErr_val_ptr );
int txpSeverityPsummary_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityPsummary_val_ptr );
int txpSeverityP5vAnalog_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityP5vAnalog_val_ptr );
int txpSeverityN5v2Analog_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityN5v2Analog_val_ptr );
int txpSeverityP3p3vAnalog_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityP3p3vAnalog_val_ptr );
int txpSeverityP3p3vDigital_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityP3p3vDigital_val_ptr );
int txpSeverityLvDigital_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityLvDigital_val_ptr );
int txpSeverityN5p2vDigital_get( txpSeverityTable_rowreq_ctx *rowreq_ctx, long * txpSeverityN5p2vDigital_val_ptr );
int txpSeverityTable_indexes_set_tbl_idx(txpSeverityTable_mib_index *tbl_idx, long txpSeverityIndex_val);
int txpSeverityTable_indexes_set(txpSeverityTable_rowreq_ctx *rowreq_ctx, long txpSeverityIndex_val);

#ifdef __cplusplus
}
#endif

#endif /* TXPSEVERITYTABLE_DATA_GET_H */
/** @} */
