/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "../../txpAlrmRxTable.h"

#include <stdio.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <stdlib.h>

#include "txpAlrmRxTable_data_access.h"

#include "../../../../lib/hl_configs/definitions.h"

void shm_handler_create(Monitor *pt_monitor_struct);
Monitor *pt_monitor_struct;

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table txpAlrmRxTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * FTNC-MIB::txpAlrmRxTable is subid 2 of txpAlrm.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.43484.2.9.1.2, length: 11
*/

/**
 * initialization for txpAlrmRxTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param txpAlrmRxTable_reg
 *        Pointer to txpAlrmRxTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
txpAlrmRxTable_init_data(txpAlrmRxTable_registration * txpAlrmRxTable_reg)
{
    DEBUGMSGTL(("verbose:txpAlrmRxTable:txpAlrmRxTable_init_data","called\n"));

    /*
     * TODO:303:o: Initialize txpAlrmRxTable data.
     */
    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    /*
     * if you are the sole writer for the file, you could
     * open it here. However, as stated earlier, we are assuming
     * the worst case, which in this case means that the file is
     * written to by someone else, and might not even exist when
     * we start up. So we can't do anything here.
     */
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

    return MFD_SUCCESS;
} /* txpAlrmRxTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
txpAlrmRxTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache)
{
    DEBUGMSGTL(("verbose:txpAlrmRxTable:txpAlrmRxTable_container_init","called\n"));
    
    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,"bad container param to txpAlrmRxTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR,"bad cache param to txpAlrmRxTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up txpAlrmRxTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = TXPALRMRXTABLE_CACHE_TIMEOUT; /* seconds */
} /* txpAlrmRxTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before txpAlrmRxTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
txpAlrmRxTable_container_shutdown(netsnmp_container *container_ptr)
{
    DEBUGMSGTL(("verbose:txpAlrmRxTable:txpAlrmRxTable_container_shutdown","called\n"));
    
    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,"bad params to txpAlrmRxTable_container_shutdown\n");
        return;
    }

} /* txpAlrmRxTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement txpAlrmRxTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  txpAlrmRxTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
txpAlrmRxTable_container_load(netsnmp_container *container)
{
     DEBUGMSGTL(("verbose:txpAlrmRxTable:txpAlrmRxTable_container_load","called\n"));

    txpAlrmRxTable_rowreq_ctx *rowreq_ctx;
    size_t count = 0;

    /*
     * temporary storage for index values
     */
        /*
         * txpAlrmRxIndex(1)/OCTETSTR/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h
         */

    char txpAlrmRxIndex[32];
    strcpy (txpAlrmRxIndex, "txpAlrmRxIndex");
    size_t txpAlrmRxIndex_len = strlen(txpAlrmRxIndex);

    shm_handler_create(pt_monitor_struct);

        /*
         * TODO:352:M: |   |-> set indexes in new txpAlrmRxTable rowreq context.
         * data context will be set from the param (unless NULL,
         *      in which case a new data context will be allocated)
         */
        rowreq_ctx = txpAlrmRxTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if(MFD_SUCCESS != txpAlrmRxTable_indexes_set(rowreq_ctx
                               , txpAlrmRxIndex, txpAlrmRxIndex_len
               )) {
            snmp_log(LOG_ERR,"error setting index while loading "
                     "txpAlrmRxTable data.\n");
            txpAlrmRxTable_release_rowreq_ctx(rowreq_ctx);
        }

        /*
         * TODO:352:r: |   |-> populate txpAlrmRxTable data context.
         * Populate data context here. (optionally, delay until row prep)
         */
    /*
     * TRANSIENT or semi-TRANSIENT data:
     * copy data or save any info needed to do it in row_prep.
     */
    /*
     * setup/save data for txpRxALMINT
     * txpRxALMINT(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
     */
    /** no mapping */
    /*
     * make sure there is enough space for txpRxALMINT data
     */
     
    char txpRxALMINT[65535];
	strcpy (txpRxALMINT, alarm_Alarm_no[pt_monitor_struct->txp_struct.txp_rx_alarm.fields.rxalmint]);
	size_t txpRxALMINT_len = strlen(txpRxALMINT);
     
    rowreq_ctx->data.txpRxALMINT_len = txpRxALMINT_len* sizeof(txpRxALMINT[0]);
    if ((NULL == rowreq_ctx->data.txpRxALMINT) ||
        (rowreq_ctx->data.txpRxALMINT_len <
         (txpRxALMINT_len* sizeof(txpRxALMINT[0])))) {
        snmp_log(LOG_ERR,"not enough space for value (txpRxALMINT)\n");
        return MFD_ERROR;
    }
    memcpy( rowreq_ctx->data.txpRxALMINT, txpRxALMINT, txpRxALMINT_len* sizeof(txpRxALMINT[0]) );
    
    /*
     * setup/save data for txpRxPOWALM
     * txpRxPOWALM(3)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
     */
    /** no mapping */
    /*
     * make sure there is enough space for txpRxPOWALM data
     */
     
    char txpRxPOWALM[65535];
	strcpy (txpRxPOWALM, alarm_Alarm_no[pt_monitor_struct->txp_struct.txp_rx_alarm.fields.rxpowalm]);
	size_t txpRxPOWALM_len = strlen(txpRxPOWALM);
     
    rowreq_ctx->data.txpRxPOWALM_len = txpRxPOWALM_len* sizeof(txpRxPOWALM[0]);
    if ((NULL == rowreq_ctx->data.txpRxPOWALM) ||
        (rowreq_ctx->data.txpRxPOWALM_len <
         (txpRxPOWALM_len* sizeof(txpRxPOWALM[0])))) {
        snmp_log(LOG_ERR,"not enough space for value (txpRxPOWALM)\n");
        return MFD_ERROR;
    }    
    memcpy( rowreq_ctx->data.txpRxPOWALM, txpRxPOWALM, txpRxPOWALM_len* sizeof(txpRxPOWALM[0]) );
    
    /*
     * setup/save data for txpRxLOS
     * txpRxLOS(4)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
     */
    /** no mapping */
    /*
     * make sure there is enough space for txpRxLOS data
     */
     
    char txpRxLOS[65535];
	strcpy (txpRxLOS, alarm_Alarm_no[pt_monitor_struct->txp_struct.txp_rx_alarm.fields.rxlos]);
	size_t txpRxLOS_len = strlen(txpRxLOS);
     
    rowreq_ctx->data.txpRxLOS_len = txpRxLOS_len* sizeof(txpRxLOS[0]);
    if ((NULL == rowreq_ctx->data.txpRxLOS) ||
        (rowreq_ctx->data.txpRxLOS_len <
         (txpRxLOS_len* sizeof(txpRxLOS[0])))) {
        snmp_log(LOG_ERR,"not enough space for value (txpRxLOS)\n");
        return MFD_ERROR;
    }
    memcpy( rowreq_ctx->data.txpRxLOS, txpRxLOS, txpRxLOS_len* sizeof(txpRxLOS[0]) );
    
    /*
     * setup/save data for txpRxLOCKERR
     * txpRxLOCKERR(5)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
     */
    /** no mapping */
    /*
     * make sure there is enough space for txpRxLOCKERR data
     */
     
    char txpRxLOCKERR[65535];
	strcpy (txpRxLOCKERR, alarm_Alarm_no[pt_monitor_struct->txp_struct.txp_rx_alarm.fields.rxlockerr]);
	size_t txpRxLOCKERR_len = strlen(txpRxLOCKERR);
     
    rowreq_ctx->data.txpRxLOCKERR_len = txpRxLOCKERR_len* sizeof(txpRxLOCKERR[0]);
    if ((NULL == rowreq_ctx->data.txpRxLOCKERR) ||
        (rowreq_ctx->data.txpRxLOCKERR_len <
         (txpRxLOCKERR_len* sizeof(txpRxLOCKERR[0])))) {
        snmp_log(LOG_ERR,"not enough space for value (txpRxLOCKERR)\n");
        return MFD_ERROR;
    }
    memcpy( rowreq_ctx->data.txpRxLOCKERR, txpRxLOCKERR, txpRxLOCKERR_len* sizeof(txpRxLOCKERR[0]) );
    
    /*
     * setup/save data for txpRXS
     * txpRXS(6)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
     */
    /** no mapping */
    /*
     * make sure there is enough space for txpRXS data
     */
     
    char txpRXS[65535];
	strcpy (txpRXS, alarm_Alarm_no[pt_monitor_struct->txp_struct.txp_rx_alarm.fields.rxs]);
	size_t txpRXS_len = strlen(txpRXS);
     
    rowreq_ctx->data.txpRXS_len = txpRXS_len* sizeof(txpRXS[0]);
    if ((NULL == rowreq_ctx->data.txpRXS) ||
        (rowreq_ctx->data.txpRXS_len <
         (txpRXS_len* sizeof(txpRXS[0])))) {
        snmp_log(LOG_ERR,"not enough space for value (txpRXS)\n");
        return MFD_ERROR;
    }    
    memcpy( rowreq_ctx->data.txpRXS, txpRXS, txpRXS_len* sizeof(txpRXS[0]) );
    
    /*
     * setup/save data for txpPRBSERRDET
     * txpPRBSERRDET(7)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
     */
    /** no mapping */
    /*
     * make sure there is enough space for txpPRBSERRDET data
     */
     
    char txpPRBSERRDET[65535];
	strcpy (txpPRBSERRDET, alarm_Alarm_no[pt_monitor_struct->txp_struct.txp_rx_alarm.fields.prbserrdet]);
	size_t txpPRBSERRDET_len = strlen(txpPRBSERRDET);
     
    rowreq_ctx->data.txpPRBSERRDET_len = txpPRBSERRDET_len* sizeof(txpPRBSERRDET[0]);
    if ((NULL == rowreq_ctx->data.txpPRBSERRDET) ||
        (rowreq_ctx->data.txpPRBSERRDET_len <
         (txpPRBSERRDET_len* sizeof(txpPRBSERRDET[0])))) {
        snmp_log(LOG_ERR,"not enough space for value (txpPRBSERRDET)\n");
        return MFD_ERROR;
    }    
    memcpy( rowreq_ctx->data.txpPRBSERRDET, txpPRBSERRDET, txpPRBSERRDET_len* sizeof(txpPRBSERRDET[0]) );
        
        /*
         * insert into table container
         */
        CONTAINER_INSERT(container, rowreq_ctx);
        ++count;

    DEBUGMSGT(("verbose:txpAlrmRxTable:txpAlrmRxTable_container_load",
               "inserted %d records\n", count));

    return MFD_SUCCESS;
} /* txpAlrmRxTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
txpAlrmRxTable_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:txpAlrmRxTable:txpAlrmRxTable_container_free","called\n"));

    /*
     * TODO:380:M: Free txpAlrmRxTable container data.
     */
} /* txpAlrmRxTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
txpAlrmRxTable_row_prep( txpAlrmRxTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:txpAlrmRxTable:txpAlrmRxTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* txpAlrmRxTable_row_prep */

/** @} */
