/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef TRAFFICPROCESSORTABLE_INTERFACE_H
#define TRAFFICPROCESSORTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "trafficProcessorTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _trafficProcessorTable_initialize_interface(trafficProcessorTable_registration * user_ctx,
                                    u_long flags);
void _trafficProcessorTable_shutdown_interface(trafficProcessorTable_registration * user_ctx);

trafficProcessorTable_registration *
trafficProcessorTable_registration_get( void );

trafficProcessorTable_registration *
trafficProcessorTable_registration_set( trafficProcessorTable_registration * newreg );

netsnmp_container *trafficProcessorTable_container_get( void );
int trafficProcessorTable_container_size( void );

    trafficProcessorTable_rowreq_ctx * trafficProcessorTable_allocate_rowreq_ctx(void *);
void trafficProcessorTable_release_rowreq_ctx(trafficProcessorTable_rowreq_ctx *rowreq_ctx);

int trafficProcessorTable_index_to_oid(netsnmp_index *oid_idx,
                            trafficProcessorTable_mib_index *mib_idx);
int trafficProcessorTable_index_from_oid(netsnmp_index *oid_idx,
                              trafficProcessorTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void trafficProcessorTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* TRAFFICPROCESSORTABLE_INTERFACE_H */
/** @} */
