/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file txpTempTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef TXPTEMPTABLE_DATA_GET_H
#define TXPTEMPTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table txpTempTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * FTNC-MIB::txpTempTable is subid 1 of txpMiscellaneous.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.43484.2.9.2.1, length: 11
*/
    /*
     * indexes
     */

    int txpTempAround_get( txpTempTable_rowreq_ctx *rowreq_ctx, char **txpTempAround_val_ptr_ptr, size_t *txpTempAround_val_ptr_len_ptr );
    int txpTempCase_get( txpTempTable_rowreq_ctx *rowreq_ctx, char **txpTempCase_val_ptr_ptr, size_t *txpTempCase_val_ptr_len_ptr );
    int txpTempTxLaser_get( txpTempTable_rowreq_ctx *rowreq_ctx, char **txpTempTxLaser_val_ptr_ptr, size_t *txpTempTxLaser_val_ptr_len_ptr );
    int txpTempRxLaser_get( txpTempTable_rowreq_ctx *rowreq_ctx, char **txpTempRxLaser_val_ptr_ptr, size_t *txpTempRxLaser_val_ptr_len_ptr );


int txpTempTable_indexes_set_tbl_idx(txpTempTable_mib_index *tbl_idx, char *txpTempIndex_val_ptr,  size_t txpTempIndex_val_ptr_len);
int txpTempTable_indexes_set(txpTempTable_rowreq_ctx *rowreq_ctx, char *txpTempIndex_val_ptr,  size_t txpTempIndex_val_ptr_len);




#ifdef __cplusplus
}
#endif

#endif /* TXPTEMPTABLE_DATA_GET_H */
/** @} */
