/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef FANTABLE_INTERFACE_H
#define FANTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "../../fanTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _fanTable_initialize_interface(fanTable_registration * user_ctx,
                                    u_long flags);
void _fanTable_shutdown_interface(fanTable_registration * user_ctx);

fanTable_registration *
fanTable_registration_get( void );

fanTable_registration *
fanTable_registration_set( fanTable_registration * newreg );

netsnmp_container *fanTable_container_get( void );
int fanTable_container_size( void );

    fanTable_rowreq_ctx * fanTable_allocate_rowreq_ctx(void *);
void fanTable_release_rowreq_ctx(fanTable_rowreq_ctx *rowreq_ctx);

int fanTable_index_to_oid(netsnmp_index *oid_idx,
                            fanTable_mib_index *mib_idx);
int fanTable_index_from_oid(netsnmp_index *oid_idx,
                              fanTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void fanTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* FANTABLE_INTERFACE_H */
/** @} */
