/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for txpSeverityTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "txpSeverityTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "FTNC-MIB/txpSeverityTable/txpSeverityTable_interface.h"

const oid txpSeverityTable_oid[] = { TXPSEVERITYTABLE_OID };
const int txpSeverityTable_oid_size = OID_LENGTH(txpSeverityTable_oid);

    txpSeverityTable_registration  txpSeverityTable_user_context;

void initialize_table_txpSeverityTable(void);
void shutdown_table_txpSeverityTable(void);


/**
 * Initializes the txpSeverityTable module
 */
void
init_txpSeverityTable(void)
{
    DEBUGMSGTL(("verbose:txpSeverityTable:init_txpSeverityTable","called\n"));

    /*
     * TODO:300:o: Perform txpSeverityTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("txpSeverityTable"))
        initialize_table_txpSeverityTable();

} /* init_txpSeverityTable */

/**
 * Shut-down the txpSeverityTable module (agent is exiting)
 */
void
shutdown_txpSeverityTable(void)
{
    if (should_init("txpSeverityTable"))
        shutdown_table_txpSeverityTable();

}

/**
 * Initialize the table txpSeverityTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_txpSeverityTable(void)
{
    txpSeverityTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:txpSeverityTable:initialize_table_txpSeverityTable","called\n"));

    /*
     * TODO:301:o: Perform txpSeverityTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize txpSeverityTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("txpSeverityTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _txpSeverityTable_initialize_interface(user_context, flags);
} /* initialize_table_txpSeverityTable */

/**
 * Shutdown the table txpSeverityTable 
 */
void
shutdown_table_txpSeverityTable(void)
{
    /*
     * call interface shutdown code
     */
    _txpSeverityTable_shutdown_interface(&txpSeverityTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
txpSeverityTable_rowreq_ctx_init(txpSeverityTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:txpSeverityTable:txpSeverityTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra txpSeverityTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* txpSeverityTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void txpSeverityTable_rowreq_ctx_cleanup(txpSeverityTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:txpSeverityTable:txpSeverityTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra txpSeverityTable rowreq cleanup.
     */
} /* txpSeverityTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
txpSeverityTable_pre_request(txpSeverityTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:txpSeverityTable:txpSeverityTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform txpSeverityTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* txpSeverityTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
txpSeverityTable_post_request(txpSeverityTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:txpSeverityTable:txpSeverityTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform txpSeverityTable post-request actions.
     */

    /*
     * check to set if any rows were changed.
     */
    if (txpSeverityTable_dirty_get()) {
        /*
         * check if request was successful. If so, this would be
         * a good place to save data to its persistent store.
         */
        if (MFD_SUCCESS == rc) {
            /*
             * save changed rows, if you haven't already
             */
        }
        
        txpSeverityTable_dirty_set(0); /* clear table dirty flag */
    }

    return MFD_SUCCESS;
} /* txpSeverityTable_post_request */


/** @{ */
